import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import api from "../../services/api";
import { getSessionUser } from "../../utils/session";

const scenarioBlank = { title: "", prompt: "", type: "multiple-choice", options: "", correctResponses: "", feedbackCorrect: "Correct — review why this response is safe.", feedbackIncorrect: "Not quite — review the hazard and try again.", order: 1, status: "pending" };
const questionBlank = { level: "basic", question: "", options: "", correctAnswer: "", points: 1, feedback: "", order: 1, status: "pending" };
const split = v => String(v || "").split("|").map(x => x.trim()).filter(Boolean);
export default function TrainingContentManagementPage() {
    const { programmeId } = useParams(), role = String(getSessionUser()?.role || "trainer").toLowerCase();
    const [scenarios, setScenarios] = useState([]), [questions, setQuestions] = useState([]), [questionBank, setQuestionBank] = useState({ requiredLevel: "basic", activeCount: 0, minimumRequired: 30, ready: false }), [s, setS] = useState(scenarioBlank), [q, setQ] = useState(questionBlank), [editS, setEditS] = useState(""), [editQ, setEditQ] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
    const load = useCallback(async () => { setLoading(true); setError(""); try { const [a, b] = await Promise.all([api.get(`/programmes/${programmeId}/manage/scenarios`), api.get(`/programmes/${programmeId}/questions`)]); setScenarios(a.data?.scenarios || []); setQuestions(b.data?.questions || []); setQuestionBank(b.data?.questionBank || { requiredLevel: "basic", activeCount: 0, minimumRequired: 30, ready: false }) } catch (e) { setError(e.response?.data?.message || "Unable to load programme content.") } finally { setLoading(false) } }, [programmeId]);
    useEffect(() => { const timer = window.setTimeout(() => load(), 0); return () => window.clearTimeout(timer) }, [load]);
    const saveScenario = async e => { e.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const body = { ...s, options: split(s.options), correctResponses: split(s.correctResponses), order: Number(s.order) }; if (!body.title.trim() || !body.prompt.trim() || !body.correctResponses.length) throw new Error("Scenario title, prompt and correct response are required."); if (editS) await api.patch(`/scenarios/${editS}`, body); else await api.post(`/programmes/${programmeId}/scenarios`, body); setSuccess(editS ? "Scenario updated." : "Scenario created as pending until approved."); setS(scenarioBlank); setEditS(""); await load() } catch (e2) { setError(e2.response?.data?.message || e2.message || "Unable to save scenario.") } finally { setSaving(false) } };
    const saveQuestion = async e => { e.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const body = { ...q, options: split(q.options), points: Number(q.points), order: Number(q.order) }; if (!body.question.trim() || body.options.length < 2 || !body.options.includes(body.correctAnswer)) throw new Error("Enter at least two options and make the correct answer exactly match one option."); if (editQ) await api.patch(`/questions/${editQ}`, body); else await api.post(`/programmes/${programmeId}/questions`, body); setSuccess(editQ ? "Question updated." : "Question created as pending until approved."); setQ(questionBlank); setEditQ(""); await load() } catch (e2) { setError(e2.response?.data?.message || e2.message || "Unable to save question.") } finally { setSaving(false) } };
    const remove = async (kind, id) => { if (!window.confirm(`Delete this ${kind}?`)) return; try { await api.delete(`/${kind === "scenario" ? "scenarios" : "questions"}/${id}`); setSuccess(`${kind} deleted.`); await load() } catch (e) { setError(e.response?.data?.message || `Unable to delete ${kind}.`) } };
    const topUpQuestionBank = async () => { setSaving(true); setError(""); setSuccess(""); try { const r = await api.post(`/programmes/${programmeId}/questions/ensure-bank`); setSuccess(r.data?.message || "Question bank updated."); await load() } catch (e) { setError(e.response?.data?.message || "Unable to update question bank.") } finally { setSaving(false) } };
    const startS = x => { setEditS(x._id); setS({ ...x, options: (x.options || []).join(" | "), correctResponses: (x.correctResponses || []).join(" | ") }) };
    const startQ = x => { setEditQ(x._id); setQ({ ...x, options: (x.options || []).join(" | ") }) };
    return <DashboardLayout role={role} title="Scenarios & Assessment Questions" subtitle="Admin and authorised Trainers can manage only programmes allowed by the server."><div className="mx-auto max-w-7xl space-y-4 p-4">{(error || success) && <div className={`rounded-lg border p-3 text-sm ${error ? "border-red-200 bg-red-50 text-red-700" : "border-green-200 bg-green-50 text-green-700"}`}>{error || success}</div>}{loading ? <div className="rounded-xl border bg-white p-8">Loading content...</div> : <div className="grid gap-5 xl:grid-cols-2">
        <Editor title={editS ? "Edit Scenario" : "Add Scenario"} onSubmit={saveScenario} saving={saving}><Input label="Title" value={s.title} set={v => setS({ ...s, title: v })} /><Text label="Prompt" value={s.prompt} set={v => setS({ ...s, prompt: v })} /><Input label="Options (separate with |)" value={s.options} set={v => setS({ ...s, options: v })} /><Input label="Correct response(s) (separate with |)" value={s.correctResponses} set={v => setS({ ...s, correctResponses: v })} /><Input label="Correct feedback" value={s.feedbackCorrect} set={v => setS({ ...s, feedbackCorrect: v })} /><Input label="Incorrect feedback" value={s.feedbackIncorrect} set={v => setS({ ...s, feedbackIncorrect: v })} /><div className="grid grid-cols-2 gap-2"><Input label="Order" type="number" value={s.order} set={v => setS({ ...s, order: v })} /><Select label="Status" value={s.status} set={v => setS({ ...s, status: v })} values={["pending", "active", "inactive"]} /></div>{editS && <button type="button" onClick={() => { setEditS(""); setS(scenarioBlank) }} className="text-xs underline">Cancel edit</button>}</Editor>
        <Editor title={editQ ? "Edit Question" : "Add Assessment Question"} onSubmit={saveQuestion} saving={saving}><Select label="Level" value={q.level} set={v => setQ({ ...q, level: v })} values={["basic", "intermediate", "high"]} /><Text label="Question" value={q.question} set={v => setQ({ ...q, question: v })} /><Input label="Options (separate with |)" value={q.options} set={v => setQ({ ...q, options: v })} /><Input label="Correct answer" value={q.correctAnswer} set={v => setQ({ ...q, correctAnswer: v })} /><Input label="Feedback" value={q.feedback} set={v => setQ({ ...q, feedback: v })} /><div className="grid grid-cols-3 gap-2"><Input label="Points" type="number" value={q.points} set={v => setQ({ ...q, points: v })} /><Input label="Order" type="number" value={q.order} set={v => setQ({ ...q, order: v })} /><Select label="Status" value={q.status} set={v => setQ({ ...q, status: v })} values={["pending", "active", "inactive"]} /></div>{editQ && <button type="button" onClick={() => { setEditQ(""); setQ(questionBlank) }} className="text-xs underline">Cancel edit</button>}</Editor>
    </div>}
        <section className={`rounded-xl border p-4 ${questionBank.ready ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}>
            <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                    <h2 className="font-bold">Assessment Question Bank</h2>
                    <p className="mt-1 text-xs text-slate-600"><b>{String(questionBank.requiredLevel || "basic").toUpperCase()}</b> level has <b>{questionBank.activeCount}</b> active questions. Minimum required: <b>{questionBank.minimumRequired || 30}</b>. Each trainee attempt uses 10 randomly selected questions with shuffled option positions.</p>
                </div>
                <button type="button" onClick={topUpQuestionBank} disabled={saving} className="rounded-lg bg-[#0b4f87] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{questionBank.ready ? "Check / Top Up Bank" : "Generate Missing Questions"}</button>
            </div>
        </section>
        <div className="grid gap-5 xl:grid-cols-2"><List title={`Scenarios (${scenarios.length})`} rows={scenarios} render={x => <><div><b>{x.order}. {x.title}</b><small className="block text-slate-500">{x.status}</small></div><div className="flex gap-2"><button onClick={() => startS(x)} className="rounded border px-2 py-1">Edit</button><button onClick={() => remove("scenario", x._id)} className="rounded border border-red-200 px-2 py-1 text-red-600">Delete</button></div></>} /><List title={`Questions (${questions.length})`} rows={questions} render={x => <><div><b>{String(x.level).toUpperCase()} · {x.order}. {x.question}</b><small className="block text-slate-500">{x.status}</small></div><div className="flex gap-2"><button onClick={() => startQ(x)} className="rounded border px-2 py-1">Edit</button><button onClick={() => remove("question", x._id)} className="rounded border border-red-200 px-2 py-1 text-red-600">Delete</button></div></>} /></div>
    </div></DashboardLayout>;
}
function Editor({ title, onSubmit, saving, children }) { return <form onSubmit={onSubmit} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-bold">{title}</h2>{children}<button disabled={saving} className="rounded-lg bg-[#0b4f87] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save"}</button></form> }
function Input({ label, value, set, type = "text" }) { return <label className="block text-xs font-semibold">{label}<input type={type} value={value ?? ""} onChange={e => set(e.target.value)} className="mt-1 h-10 w-full rounded border px-3 font-normal" /></label> }
function Text({ label, value, set }) { return <label className="block text-xs font-semibold">{label}<textarea value={value ?? ""} onChange={e => set(e.target.value)} className="mt-1 min-h-20 w-full rounded border p-3 font-normal" /></label> }
function Select({ label, value, set, values }) { return <label className="block text-xs font-semibold">{label}<select value={value} onChange={e => set(e.target.value)} className="mt-1 h-10 w-full rounded border px-2 font-normal">{values.map(v => <option key={v} value={v}>{v[0].toUpperCase() + v.slice(1)}</option>)}</select></label> }
function List({ title, rows, render }) { return <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">{title}</h2><div className="mt-3 space-y-2">{rows.length ? rows.map(x => <div key={x._id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 p-3 text-xs">{render(x)}</div>) : <p className="text-xs text-slate-500">No content yet.</p>}</div></section> }
