const TrainingProgramme = require("../models/TrainingProgramme");
const TrainingAssignment = require("../models/TrainingAssignment");
const LearningSection = require("../models/LearningSection");
const TrainingProgress = require("../models/TrainingProgress");
const Scenario = require("../models/Scenario");
const AssessmentQuestion = require("../models/AssessmentQuestion");
const AssessmentAttempt = require("../models/AssessmentAttempt");

const allowed = async (req, programmeId) => {
    const p = await TrainingProgramme.findById(programmeId);
    if (!p) return null;
    if (req.user.role === "admin") return p;
    const uid = String(req.user.id);
    if (req.user.role === "trainer" && (String(p.owner) === uid || (p.authorizedTrainers || []).some(x => String(x) === uid))) return p;
    return false;
};
const assigned = async (req, programmeId) => TrainingAssignment.findOne({ programme: programmeId, trainee: req.user.id, status: "active" });
const getProgress = async (req, programmeId, assignment) => {
    let p = await TrainingProgress.findOne({ trainee: req.user.id, programme: programmeId });
    if (!p) p = await TrainingProgress.create({ trainee: req.user.id, programme: programmeId, assignment: assignment._id, status: "in-progress", startedAt: new Date(), lastAccessedAt: new Date() });
    return p;
};
const updateStage = (p) => { if (p.highPassed) { p.currentStage = "completed"; p.status = "completed"; p.progress = 100; p.completedAt = p.completedAt || new Date(); } else if (p.intermediatePassed) { p.currentStage = "high"; p.progress = Math.max(p.progress, 80); } else if (p.basicPassed) { p.currentStage = "intermediate"; p.progress = Math.max(p.progress, 65); } else if (p.scenarioCompleted) { p.currentStage = "basic"; p.progress = Math.max(p.progress, 50); } else if (p.learningCompleted) { p.currentStage = "scenario"; p.progress = Math.max(p.progress, 40); } else { p.currentStage = "learning"; } };

exports.listScenarios = async (req, res) => { try { const p = await allowed(req, req.params.programmeId); if (p === null) return res.status(404).json({ message: "Programme not found" }); if (!p) return res.status(403).json({ message: "Not authorised for this programme" }); res.json({ scenarios: await Scenario.find({ programme: p._id }).sort({ order: 1 }) }); } catch (e) { res.status(500).json({ message: "Unable to load scenarios" }); } };
exports.createScenario = async (req, res) => { try { const p = await allowed(req, req.params.programmeId); if (!p) return res.status(p === null ? 404 : 403).json({ message: p === null ? "Programme not found" : "Not authorised" }); const s = await Scenario.create({ ...req.body, programme: p._id, createdBy: req.user.id }); res.status(201).json({ scenario: s }); } catch (e) { res.status(400).json({ message: e.message }); } };
exports.updateScenario = async (req, res) => { try { const s = await Scenario.findById(req.params.scenarioId); if (!s) return res.status(404).json({ message: "Scenario not found" }); const p = await allowed(req, s.programme); if (!p) return res.status(403).json({ message: "Not authorised" });["title", "prompt", "type", "options", "correctResponses", "feedbackCorrect", "feedbackIncorrect", "order", "status"].forEach(k => { if (req.body[k] !== undefined) s[k] = req.body[k] }); s.updatedBy = req.user.id; await s.save(); res.json({ scenario: s }); } catch (e) { res.status(400).json({ message: e.message }); } };
exports.deleteScenario = async (req, res) => { try { const s = await Scenario.findById(req.params.scenarioId); if (!s) return res.status(404).json({ message: "Scenario not found" }); const p = await allowed(req, s.programme); if (!p) return res.status(403).json({ message: "Not authorised" }); s.status = "inactive"; s.updatedBy = req.user.id; await s.save(); res.json({ scenario: s }); } catch (e) { res.status(500).json({ message: "Unable to deactivate scenario" }); } };

exports.listQuestions = async (req, res) => { try { const p = await allowed(req, req.params.programmeId); if (!p) return res.status(p === null ? 404 : 403).json({ message: "Not authorised" }); const q = { programme: p._id }; if (req.query.level) q.level = req.query.level; res.json({ questions: await AssessmentQuestion.find(q).sort({ level: 1, order: 1 }) }); } catch (e) { res.status(500).json({ message: "Unable to load questions" }); } };
exports.createQuestion = async (req, res) => { try { const p = await allowed(req, req.params.programmeId); if (!p) return res.status(p === null ? 404 : 403).json({ message: "Not authorised" }); if (!req.body.options?.includes(req.body.correctAnswer)) return res.status(400).json({ message: "Correct answer must be one of the options" }); const q = await AssessmentQuestion.create({ ...req.body, programme: p._id, createdBy: req.user.id }); res.status(201).json({ question: q }); } catch (e) { res.status(400).json({ message: e.message }); } };
exports.updateQuestion = async (req, res) => { try { const q = await AssessmentQuestion.findById(req.params.questionId); if (!q) return res.status(404).json({ message: "Question not found" }); const p = await allowed(req, q.programme); if (!p) return res.status(403).json({ message: "Not authorised" });["level", "question", "options", "correctAnswer", "points", "feedback", "order", "status"].forEach(k => { if (req.body[k] !== undefined) q[k] = req.body[k] }); if (!q.options.includes(q.correctAnswer)) return res.status(400).json({ message: "Correct answer must be one of the options" }); q.updatedBy = req.user.id; await q.save(); res.json({ question: q }); } catch (e) { res.status(400).json({ message: e.message }); } };
exports.deleteQuestion = async (req, res) => { try { const q = await AssessmentQuestion.findById(req.params.questionId); if (!q) return res.status(404).json({ message: "Question not found" }); const p = await allowed(req, q.programme); if (!p) return res.status(403).json({ message: "Not authorised" }); q.status = "inactive"; q.updatedBy = req.user.id; await q.save(); res.json({ question: q }); } catch (e) { res.status(500).json({ message: "Unable to deactivate question" }); } };

exports.completeSection = async (req, res) => { try { const a = await assigned(req, req.params.programmeId); if (!a) return res.status(403).json({ message: "Programme is not assigned to you" }); const sec = await LearningSection.findOne({ _id: req.params.sectionId, programme: req.params.programmeId, status: "active" }); if (!sec) return res.status(404).json({ message: "Learning section not found" }); const p = await getProgress(req, req.params.programmeId, a); if (!p.completedSections.some(x => String(x) === String(sec._id))) p.completedSections.push(sec._id); const total = await LearningSection.countDocuments({ programme: req.params.programmeId, status: "active" }); p.learningCompleted = total > 0 && p.completedSections.length >= total; p.status = "in-progress"; p.lastAccessedAt = new Date(); p.progress = Math.max(p.progress, total ? Math.round((p.completedSections.length / total) * 40) : 0); updateStage(p); await p.save(); res.json({ progress: p }); } catch (e) { res.status(500).json({ message: "Unable to record section completion" }); } };
exports.getTraineeProgress = async (req, res) => { try { const a = await assigned(req, req.params.programmeId); if (!a) return res.status(403).json({ message: "Programme is not assigned to you" }); const p = await getProgress(req, req.params.programmeId, a); updateStage(p); await p.save(); res.json({ progress: p }); } catch (e) { res.status(500).json({ message: "Unable to load progress" }); } };
exports.getTraineeScenarios = async (req, res) => { try { const a = await assigned(req, req.params.programmeId); if (!a) return res.status(403).json({ message: "Programme is not assigned to you" }); const p = await getProgress(req, req.params.programmeId, a); if (!p.learningCompleted) return res.status(403).json({ code: "LEARNING_INCOMPLETE", message: "Complete all learning sections before starting the exercise." }); const scenarios = await Scenario.find({ programme: req.params.programmeId, status: "active" }).sort({ order: 1 }).select("title prompt type options order"); res.json({ scenarios }); } catch (e) { res.status(500).json({ message: "Unable to load scenarios" }); } };
exports.submitScenario = async (req, res) => { try { const a = await assigned(req, req.params.programmeId); if (!a) return res.status(403).json({ message: "Programme is not assigned to you" }); const p = await getProgress(req, req.params.programmeId, a); if (!p.learningCompleted) return res.status(403).json({ message: "Complete learning first" }); const s = await Scenario.findOne({ _id: req.params.scenarioId, programme: req.params.programmeId, status: "active" }); if (!s) return res.status(404).json({ message: "Scenario not found" }); const given = (Array.isArray(req.body.responses) ? req.body.responses : [req.body.response]).filter(Boolean).map(x => String(x).trim().toLowerCase()).sort(); const correct = (s.correctResponses || []).map(x => String(x).trim().toLowerCase()).sort(); const ok = given.length === correct.length && given.every((x, i) => x === correct[i]); if (ok) { const total = await Scenario.countDocuments({ programme: req.params.programmeId, status: "active" }); const completedKey = `scenario:${s._id}`; p.trainingSection = p.trainingSection || ""; const done = new Set((p.trainingSection || "").split("|").filter(x => x.startsWith("scenario:"))); done.add(completedKey); p.trainingSection = [...done].join("|"); p.scenarioCompleted = total > 0 && done.size >= total; updateStage(p); await p.save(); } res.json({ correct: ok, feedback: ok ? s.feedbackCorrect : s.feedbackIncorrect, progress: p }); } catch (e) { res.status(500).json({ message: "Unable to submit scenario" }); } };

const eligible = async (req, programmeId, level) => { const a = await assigned(req, programmeId); if (!a) return { error: [403, "Programme is not assigned to you"] }; const p = await getProgress(req, programmeId, a); if (level === "basic" && !p.learningCompleted) return { error: [403, "Complete all learning sections first"] }; const sc = await Scenario.countDocuments({ programme: programmeId, status: "active" }); if (level === "basic" && sc > 0 && !p.scenarioCompleted) return { error: [403, "Complete the scenario exercise first"] }; if (level === "intermediate" && !p.basicPassed) return { error: [403, "Pass Basic before starting Intermediate"] }; if (level === "high" && !p.intermediatePassed) return { error: [403, "Pass Intermediate before starting High"] }; return { a, p }; };
exports.getAssessment = async (req, res) => { try { const level = req.params.level; const e = await eligible(req, req.params.programmeId, level); if (e.error) return res.status(e.error[0]).json({ code: "LEVEL_LOCKED", message: e.error[1] }); const qs = await AssessmentQuestion.find({ programme: req.params.programmeId, level, status: "active" }).sort({ order: 1 }).select("question options points order"); if (!qs.length) return res.status(404).json({ message: "No active questions are available for this level" }); res.json({ level, questions: qs }); } catch (e) { res.status(500).json({ message: "Unable to load assessment" }); } };
exports.submitAssessment = async (req, res) => { try { const level = req.params.level; const e = await eligible(req, req.params.programmeId, level); if (e.error) return res.status(e.error[0]).json({ code: "LEVEL_LOCKED", message: e.error[1] }); const programme = await TrainingProgramme.findById(req.params.programmeId); const qs = await AssessmentQuestion.find({ programme: req.params.programmeId, level, status: "active" }).sort({ order: 1 }); if (!qs.length) return res.status(404).json({ message: "No active questions are available" }); const map = new Map((req.body.answers || []).map(x => [String(x.questionId), String(x.answer ?? "")])); let score = 0, total = 0; const answers = qs.map(q => { const ans = map.get(String(q._id)) || ""; const correct = ans === q.correctAnswer; total += q.points; if (correct) score += q.points; return { question: q._id, answer: ans, correct, pointsAwarded: correct ? q.points : 0 }; }); const percentage = total ? Math.round((score / total) * 10000) / 100 : 0; const passed = percentage >= programme.passMark; const attemptNumber = await AssessmentAttempt.countDocuments({ trainee: req.user.id, programme: programme._id, level }) + 1; const attempt = await AssessmentAttempt.create({ trainee: req.user.id, programme: programme._id, assignment: e.a._id, level, answers, score, totalPoints: total, percentage, passed, attemptNumber }); if (passed) { if (level === "basic") e.p.basicPassed = true; if (level === "intermediate") e.p.intermediatePassed = true; if (level === "high") e.p.highPassed = true; updateStage(e.p); await e.p.save(); } res.status(201).json({ attempt: { _id: attempt._id, level, score, totalPoints: total, percentage, passed, attemptNumber }, progress: e.p }); } catch (err) { res.status(500).json({ message: "Unable to submit assessment" }); } };
exports.getMyResults = async (req, res) => { try { res.json({ attempts: await AssessmentAttempt.find({ trainee: req.user.id }).populate("programme", "title programmeType").sort({ submittedAt: -1 }) }); } catch (e) { res.status(500).json({ message: "Unable to load results" }); } };
