const router = require('express').Router();
const { rateLimit } = require('express-rate-limit');
const authenticate = require('../middleware/authenticate');
const authorize = require('../middleware/authorize');
const c = require('../controllers/safetySimulationController');
router.use(authenticate);
const managers = authorize('admin', 'trainer');
const players = authorize('trainee');
const limiter = rateLimit({ windowMs: 60 * 1000, limit: 100, keyGenerator: req => req.user.id, standardHeaders: 'draft-8', legacyHeaders: false, message: { message: 'Too many interactions. Wait briefly and try again.' } });
router.get('/options', managers, c.options);
router.get('/results', managers, c.results);
router.post('/preview', managers, c.preview);
router.post('/samples', managers, c.addSamples);
router.get('/', authorize('admin', 'trainer', 'trainee'), c.list);
router.post('/', managers, c.create);
router.get('/:id', authorize('admin', 'trainer', 'trainee'), c.get);
router.put('/:id', managers, c.update);
router.patch('/:id/status', managers, c.status);
router.post('/:id/duplicate', managers, c.duplicate);
router.delete('/:id', authorize('admin'), c.archive);
router.get('/:id/leaderboard', authorize('admin', 'trainer', 'trainee'), c.leaderboard);
router.post('/:id/attempts/start', players, limiter, c.start);
router.get('/:id/attempts/:attemptId', players, c.attempt);
router.post('/:id/attempts/:attemptId/action', players, limiter, c.action);
router.post('/:id/attempts/:attemptId/complete', players, limiter, c.complete);
module.exports = router;
