const express = require('express');
const authenticate = require('../middleware/authenticate');
const authorize = require('../middleware/authorize');
const active = require('../middleware/checkActiveStatus');
const upload = require('../middleware/uploadPanorama');
const c = require('../controllers/sprint2ApiController');
const programmeController = require('../controllers/trainingProgrammeController');
const sectionController = require('../controllers/learningSectionController');
const legacySprint2 = require('../controllers/sprint2Controller');
const uploadTrainingImage = require('../middleware/uploadTrainingImage');

const r = express.Router();
r.use(authenticate, active);
r.get('/programmes', authorize('admin', 'trainer', 'trainee'), c.listProgrammes);
r.post('/programmes', authorize('admin', 'trainer'), programmeController.createTrainingProgramme);
r.patch('/programmes/:programmeId', authorize('admin', 'trainer'), programmeController.updateTrainingProgramme);
r.delete('/programmes/:programmeId', authorize('admin', 'trainer'), programmeController.deleteTrainingProgramme);
r.get('/programmes/:programmeId/sections', authorize('admin', 'trainer'), sectionController.getLearningSections);
r.post('/programmes/:programmeId/sections', authorize('admin', 'trainer'), uploadTrainingImage.single('image'), sectionController.createLearningSection);
r.patch('/programmes/:programmeId/sections/:sectionId', authorize('admin', 'trainer'), uploadTrainingImage.single('image'), sectionController.updateLearningSection);
r.patch('/sections/:sectionId', authorize('admin', 'trainer'), (req, res, next) => { req.params.programmeId = req.body.programmeId || req.query.programmeId; if (!req.params.programmeId) return res.status(400).json({ message: 'programmeId is required to update a section safely.' }); next(); }, uploadTrainingImage.single('image'), sectionController.updateLearningSection);
r.put('/programmes/:programmeId/sections/reorder', authorize('admin', 'trainer'), sectionController.reorderLearningSections);

r.post('/assignments', authorize('admin'), c.createAssignment);
r.get('/trainee/training', authorize('trainee'), c.traineeTraining);
r.get('/trainee/warehouse-tour', authorize('trainee'), c.warehouseTour);
r.post('/programmes/:id/sections/:sectionId/complete', authorize('trainee'), c.completeSection);
r.get('/panoramas', authorize('admin'), c.listPanoramas);
r.post('/panoramas', authorize('admin'), upload.single('panorama'), c.createPanorama);
r.patch('/panoramas/:id', authorize('admin'), upload.single('panorama'), c.updatePanorama);
r.get('/programmes/:id/environment', authorize('admin', 'trainer', 'trainee'), c.environment);
r.get('/programmes/:id/scenarios', authorize('trainee'), c.traineeScenarios);
r.get('/programmes/:id/manage/scenarios', authorize('admin', 'trainer'), c.manageScenarios);
r.post('/programmes/:id/scenarios', authorize('admin', 'trainer'), c.createScenario);
r.patch('/scenarios/:scenarioId', authorize('admin', 'trainer'), legacySprint2.updateScenario);
r.delete('/scenarios/:scenarioId', authorize('admin', 'trainer'), legacySprint2.deleteScenario);
r.get('/programmes/:id/questions', authorize('admin', 'trainer'), c.manageQuestions);
r.post('/programmes/:id/questions', authorize('admin', 'trainer'), c.createQuestion);
r.patch('/questions/:questionId', authorize('admin', 'trainer'), c.updateQuestion);
r.delete('/questions/:questionId', authorize('admin', 'trainer'), legacySprint2.deleteQuestion);
r.get('/programmes/:id/assessments/:level', authorize('trainee'), c.getAssessment);
r.post('/programmes/:id/assessments/:level/submit', authorize('trainee'), c.submitAssessment);
r.post('/assessments/:level/submit', authorize('trainee'), (req, res, next) => { req.params.id = req.body.programmeId; if (!req.params.id) return res.status(400).json({ message: 'programmeId is required.' }); next(); }, c.submitAssessment);
r.get('/trainee/results', authorize('admin', 'trainer', 'trainee'), c.results);
module.exports = r;
