const express = require("express"); const r = express.Router();
const authenticate = require("../middleware/authenticate"), authorize = require("../middleware/authorize"), active = require("../middleware/checkActiveStatus"), c = require("../controllers/sprint2Controller");
r.use(authenticate, active);
r.get("/programmes/:programmeId/scenarios", authorize("admin", "trainer"), c.listScenarios);
r.post("/programmes/:programmeId/scenarios", authorize("admin", "trainer"), c.createScenario);
r.patch("/scenarios/:scenarioId", authorize("admin", "trainer"), c.updateScenario);
r.delete("/scenarios/:scenarioId", authorize("admin", "trainer"), c.deleteScenario);
r.get("/programmes/:programmeId/questions", authorize("admin", "trainer"), c.listQuestions);
r.post("/programmes/:programmeId/questions", authorize("admin", "trainer"), c.createQuestion);
r.patch("/questions/:questionId", authorize("admin", "trainer"), c.updateQuestion);
r.delete("/questions/:questionId", authorize("admin", "trainer"), c.deleteQuestion);
r.get("/trainee/:programmeId/progress", authorize("trainee"), c.getTraineeProgress);
r.post("/trainee/:programmeId/sections/:sectionId/complete", authorize("trainee"), c.completeSection);
r.get("/trainee/:programmeId/scenarios", authorize("trainee"), c.getTraineeScenarios);
r.post("/trainee/:programmeId/scenarios/:scenarioId/submit", authorize("trainee"), c.submitScenario);
r.get("/trainee/:programmeId/assessments/:level", authorize("trainee"), c.getAssessment);
r.post("/trainee/:programmeId/assessments/:level/submit", authorize("trainee"), c.submitAssessment);
r.get("/trainee/results", authorize("trainee"), c.getMyResults);
module.exports = r;
