// Forty-five distinct, playable safety scenarios (5 per level per training module).
// Scenario-specific decisions are data-driven and scored by the same authoritative
// engine as manually authored 360-degree safety missions. No random/automatic points.
const STEP = (name, issue, safe, unsafe) => ({ name, issue, safe, unsafe });
const M = (title, mission, ...steps) => ({ title, mission, steps });

const SCENARIOS = {
  'manual-handling': {
    cover: '/panoramas/manual-handling.png', secondCover: '/panoramas/loading-dispatch.png',
    area: 'Warehouse inspection zone', desk: 'Dispatch supervisor station',
    levels: {
      beginner: [
        M('Safe Box Lift', 'Prepare a small carton for a safe individual lift.', STEP('Carton label', 'The carton has no visible weight information.', 'Check the weight and ask before lifting', 'Lift without checking the weight'), STEP('Floor route', 'A loose wrapper obstructs the walking route.', 'Remove the wrapper and clear the route', 'Carry the carton over the obstruction'), STEP('Lifting position', 'The carton is placed beyond easy reach.', 'Move close and use a stable lifting stance', 'Twist and reach with the loaded carton')),
        M('Keep the Walkway Clear', 'Restore a safe pedestrian route before moving stock.', STEP('Walkway boxes', 'Boxes are stored across the marked pedestrian lane.', 'Move boxes to an approved storage space', 'Step between the boxes while carrying'), STEP('Floor debris', 'Plastic strapping creates a trip hazard.', 'Collect and dispose of strapping', 'Leave strapping for the next shift'), STEP('Exit sign', 'The route to an emergency exit is partly blocked.', 'Restore the full exit clearance', 'Stack a load against the exit')),
        M('Check Before You Carry', 'Assess an unfamiliar package before carrying it.', STEP('Delivery label', 'The contents and handling instructions are unclear.', 'Read the label and confirm handling instructions', 'Assume the contents are lightweight'), STEP('Grip points', 'Packaging is torn near the carrying handles.', 'Select a secure grip or suitable equipment', 'Carry using the torn handle'), STEP('Destination shelf', 'The destination shelf is above comfortable reach.', 'Request an appropriate handling aid', 'Stretch overhead while holding the box')),
        M('Trolley Pre-Use Check', 'Inspect a warehouse trolley before transferring cartons.', STEP('Trolley wheels', 'One wheel drags and turns unevenly.', 'Remove the defective trolley from service', 'Push the defective trolley quickly'), STEP('Trolley capacity', 'The load limit plate is partly obscured.', 'Check the rated limit against the load', 'Ignore the rated load limit'), STEP('Trolley route', 'The route crosses a blind corner.', 'Plan visibility and a controlled crossing', 'Accelerate around the blind corner')),
        M('Orderly Dispatch Staging', 'Stage boxes without creating strain or obstructions.', STEP('Stack height', 'Cartons are stacked with heavy items at the top.', 'Rearrange heavy items at safer low levels', 'Pull the bottom carton out'), STEP('Staging floor', 'An uneven pallet occupies the staging area.', 'Replace or isolate the damaged pallet', 'Place more weight on the uneven pallet'), STEP('Picking lane', 'A temporary stack extends into the picking lane.', 'Move the stack within marked boundaries', 'Carry goods through the narrow gap')),
      ],
      intermediate: [
        M('Coordinated Team Lift', 'Organise a team lift for a long, awkward load.', STEP('Load assessment', 'The load is long and difficult for one person to control.', 'Confirm the weight and agree a team-lift plan', 'Begin the lift without coordinating'), STEP('Team communication', 'The second handler cannot see the first handler clearly.', 'Agree signals and a shared count', 'Lift while the second handler is distracted'), STEP('Put-down zone', 'The destination has no clear space for the load.', 'Clear and prepare the put-down area', 'Lower the load onto scattered cartons')),
        M('Loading Ramp Transfer', 'Move a load across a ramp without losing control.', STEP('Ramp surface', 'The ramp is damp near the dock edge.', 'Inspect and treat the slip risk before moving', 'Rush over the damp patch'), STEP('Dock restraint', 'The vehicle restraint has not been confirmed.', 'Verify the vehicle and dock are secured', 'Enter the vehicle without checking'), STEP('Load control', 'The load can roll when released on the ramp.', 'Use approved load restraint and assistance', 'Release the load on the slope')),
        M('Spill and Load Response', 'Stop an unsafe transfer following a warehouse spill.', STEP('Liquid spill', 'Liquid has spread across the handling route.', 'Isolate the spill and follow the cleanup procedure', 'Wheel stock straight through the spill'), STEP('Pallet base', 'A pallet is wet and shows damaged deck boards.', 'Use a sound replacement pallet', 'Lift stock on the damaged pallet'), STEP('Pedestrian diversion', 'Pedestrians continue toward the affected zone.', 'Set a safe diversion route and warning', 'Allow people through without warning')),
        M('Roll Cage Stabilisation', 'Prepare a loaded roll cage for safe movement.', STEP('Cage door', 'The cage gate swings open during movement.', 'Close and secure the cage gate', 'Push with the cage gate unsecured'), STEP('Stacked cartons', 'The top cartons obstruct forward vision.', 'Reduce or rearrange the load for visibility', 'Push while unable to see ahead'), STEP('Cage brakes', 'The parking brake does not hold the cage.', 'Tag the cage and choose working equipment', 'Leave the cage on a slope')),
        M('Repetitive Picking Rotation', 'Control manual-handling strain during a busy picking shift.', STEP('Pick frequency', 'The worker repeats the same awkward reach many times.', 'Plan task rotation and suitable rest breaks', 'Ignore symptoms and keep the same motion'), STEP('Pick height', 'Fast-moving products are stored above shoulder level.', 'Move frequently picked stock to safer reach', 'Reach overhead with heavy goods repeatedly'), STEP('Handling aid', 'A suitable height-adjustable aid is available.', 'Set up and use the approved handling aid', 'Avoid the aid to save a few seconds')),
      ],
      advanced: [
        M('Narrow Aisle Emergency', 'Control a material transfer when aisle visibility suddenly drops.', STEP('Aisle junction', 'An opposing trolley approaches a blind junction.', 'Stop and establish a clear right of way', 'Force the trolley through the gap'), STEP('Damaged load', 'A carton begins to slide off the moving load.', 'Stop, secure and re-check load stability', 'Catch the carton while moving'), STEP('Escape route', 'The nearest emergency access lane is partly obstructed.', 'Stop operations and restore emergency access', 'Park the trolley in the emergency lane')),
        M('Mixed Pallet Risk Review', 'Review a mixed, uneven pallet before dispatch.', STEP('Weight distribution', 'Heavy goods have been placed above fragile boxes.', 'Rebuild the pallet with stable load distribution', 'Ship the top-heavy pallet'), STEP('Pallet wrap', 'Stretch wrap is loose along one corner.', 'Apply approved load restraint after rechecking', 'Ignore the loose wrapping'), STEP('Pallet rating', 'The capacity of the pallet is not verified.', 'Verify the pallet and equipment capacities', 'Assume the pallet supports any load')),
        M('Urgent Order Pressure', 'Handle a last-minute dispatch order without bypassing controls.', STEP('Dispatch deadline', 'A supervisor requests immediate movement without a safe plan.', 'Explain the risk and agree a safe sequence', 'Skip the handling check to meet the deadline'), STEP('Equipment inspection', 'The only available trolley has a fault label.', 'Keep the trolley out of use and source an approved one', 'Remove the fault label and use the trolley'), STEP('Busy crossing', 'Vehicle traffic is heavy near the loading bay.', 'Use authorised crossing and traffic controls', 'Shortcut between moving vehicles')),
        M('Contractor Delivery Handover', 'Coordinate a mixed-load handover with a visiting delivery crew.', STEP('Weight documentation', 'The delivery manifest omits a heavy item weight.', 'Hold the lift until the weight is verified', 'Ask the driver to guess the weight'), STEP('Shared handling plan', 'The visiting crew has not agreed on who leads the lift.', 'Confirm roles and an agreed handling method', 'Lift independently with no shared plan'), STEP('Drop-off space', 'The handover area is shared with active forklifts.', 'Separate pedestrian and vehicle movement', 'Unload beside moving forklifts')),
        M('Damaged Goods Recovery', 'Recover stock after a collapsed stack without a second incident.', STEP('Collapsed stack', 'Several cartons rest under an unstable leaning pallet.', 'Isolate the area and assess structural stability', 'Pull cartons from beneath the pallet'), STEP('Recovery equipment', 'The available jack may not support the displaced weight.', 'Verify capacity and arrange suitable equipment', 'Overload the jack to lift the stack'), STEP('Incident escalation', 'The fall may have damaged nearby storage racking.', 'Report the impact and keep the rack isolated', 'Return goods to the rack without an inspection')),
      ],
    },
  },
  'working-at-height': {
    cover: '/panoramas/working-height.png', secondCover: '/panoramas/logistics-indoor.png',
    area: 'Elevated-work preparation zone', desk: 'Ground-level safety desk',
    levels: {
      beginner: [
        M('Ladder Inspection', 'Recognise an unsafe ladder before any access attempt.', STEP('Ladder rung', 'A ladder rung is bent and no longer secure.', 'Tag and remove the damaged ladder from service', 'Climb using the undamaged rungs'), STEP('Ladder feet', 'The rubber feet are missing on one side.', 'Select an inspected ladder with sound feet', 'Place loose packing under the ladder'), STEP('Access surface', 'The chosen floor area is uneven and cluttered.', 'Clear and assess the access surface', 'Use the ladder on uneven cartons')),
        M('Keep the Edge Protected', 'Identify guardrail and opening hazards before work.', STEP('Platform guardrail', 'A section of guardrail is loose.', 'Close access and arrange a guardrail repair', 'Lean against the loose guardrail'), STEP('Floor opening', 'A maintenance hatch is uncovered.', 'Secure the opening with approved controls', 'Step around the unprotected opening'), STEP('Access gate', 'The access gate does not latch closed.', 'Prevent entry until the gate is secured', 'Tie the gate open during the task')),
        M('Control Falling Tools', 'Prepare a safe maintenance zone below overhead work.', STEP('Hand tools', 'Tools are resting near an elevated edge.', 'Secure tools using the approved method', 'Place tools loosely along the edge'), STEP('Ground traffic', 'Workers pass directly below the planned work.', 'Set a controlled exclusion zone', 'Continue work over passing pedestrians'), STEP('Loose materials', 'Small fittings could fall from an unprotected tray.', 'Contain and secure the fittings', 'Carry loose fittings in an open hand')),
        M('Safe Platform Entry', 'Check access and exit points before entering a platform.', STEP('Platform access', 'An access gate sticks in the open position.', 'Report the gate defect and use approved access', 'Use the platform with the gate open'), STEP('Platform label', 'The inspection record is out of date.', 'Confirm a current inspection and authorisation', 'Assume the platform is safe'), STEP('Work surface', 'Packaging blocks the path to the work position.', 'Clear the route before accessing the work area', 'Climb over packaging to reach the platform')),
        M('Weather and Access Check', 'Assess outdoor elevated work before starting.', STEP('Wind conditions', 'Strong gusts could destabilise the proposed operation.', 'Check operational wind limits and postpone if needed', 'Proceed without checking wind limits'), STEP('Wet platform', 'Water has collected on the elevated surface.', 'Address slip hazards before entry', 'Walk quickly across the wet surface'), STEP('Access plan', 'The safe route back to ground level is not clear.', 'Confirm the entry and exit procedure', 'Begin without a return route')),
      ],
      intermediate: [
        M('Scaffold Readiness Review', 'Verify scaffold condition and authorisation for the planned task.', STEP('Inspection tag', 'The scaffold inspection tag is missing.', 'Confirm inspection status with the competent person', 'Use the scaffold without evidence of inspection'), STEP('Working deck', 'A board appears displaced from the deck.', 'Close access and have the deck corrected', 'Step across the gap'), STEP('Material storage', 'Materials are piled at an exposed platform edge.', 'Secure materials within approved limits', 'Leave loose material by the edge')),
        M('Mobile Platform Setup', 'Prepare mobile access equipment for maintenance work.', STEP('Ground slope', 'The equipment sits on ground outside its approved setup condition.', 'Reposition and verify ground suitability', 'Operate the platform on the slope'), STEP('Travel route', 'Overhead obstruction lies across the travel path.', 'Plan clearance before moving the platform', 'Drive beneath the obstruction without checking'), STEP('Entry gate', 'The platform gate has been tied back.', 'Restore and test the gate before use', 'Operate with the gate held open')),
        M('Electrical Work Overhead', 'Coordinate elevated maintenance around electrical services.', STEP('Overhead cable', 'A live-service label is visible near the work.', 'Identify the service and follow isolation requirements', 'Work close to the cable without assessment'), STEP('Tool selection', 'An unapproved tool is ready at the access point.', 'Select equipment approved for the assessed task', 'Use any available metal tool'), STEP('Work authorisation', 'The site permit does not cover electrical proximity.', 'Stop and obtain the correct authorisation', 'Proceed using the unrelated permit')),
        M('Roof Access Control', 'Establish controls before roof-level inspection.', STEP('Roof opening', 'An access hatch is open beside the inspection route.', 'Protect the opening using the approved method', 'Walk next to the open hatch'), STEP('Fragile panel', 'A translucent roof panel may not support weight.', 'Identify and prevent access to fragile surfaces', 'Step on the translucent panel'), STEP('Rescue provision', 'The roof work plan has no clear rescue arrangements.', 'Confirm suitable emergency and rescue arrangements', 'Rely on emergency services without a site plan')),
        M('Overhead Maintenance Handover', 'Transfer an elevated work area between maintenance shifts.', STEP('Platform condition', 'An earlier inspection recorded a temporary defect.', 'Verify closure of the defect before reuse', 'Assume the earlier team resolved it'), STEP('Tool inventory', 'One tool is missing from the tool count.', 'Locate or account for the missing tool', 'Leave without investigating the missing tool'), STEP('Barrier handover', 'The exclusion zone is being removed too early.', 'Keep controls until work is completed and clear', 'Remove barriers while overhead work continues')),
      ],
      advanced: [
        M('Unplanned Rescue Scenario', 'Respond when an elevated worker cannot descend normally.', STEP('Rescue communication', 'An elevated worker signals that the platform has stopped.', 'Activate the site rescue procedure and contact trained responders', 'Tell the worker to climb over the guardrail'), STEP('Area below', 'Pedestrians are gathering under the stopped platform.', 'Secure the ground area and manage access', 'Allow people to stand directly below'), STEP('Emergency controls', 'The emergency-lowering method has not been verified.', 'Follow the equipment-specific rescue instructions', 'Attempt an untrained improvised lowering')),
        M('Competing Trades at Height', 'Coordinate two teams working above the same route.', STEP('Overlapping work', 'Two contractors plan activities on different levels.', 'Coordinate work sequencing and exclusion controls', 'Allow simultaneous conflicting work'), STEP('Permit scope', 'One task permit does not describe the changed access plan.', 'Reassess and update authorisation before work', 'Use the old permit for the changed activity'), STEP('Dropped-object plan', 'Materials can pass between the two work zones.', 'Install approved containment and separation', 'Carry loose items over workers below')),
        M('Structural Access Uncertainty', 'Avoid using elevated equipment after an unexpected impact.', STEP('Rack impact', 'A forklift struck the base of nearby storage racking.', 'Isolate the zone and request competent inspection', 'Access the rack for an immediate repair'), STEP('Access device', 'A work platform was near the impact and may be affected.', 'Inspect and verify the device before use', 'Assume no visible damage means safe'), STEP('Urgent task', 'Management asks for the work to continue immediately.', 'Escalate the risk and agree a safe alternative', 'Proceed without authorisation')),
        M('Changing Weather at Height', 'Safely stop exposed work when conditions deteriorate.', STEP('Weather alert', 'The forecast now exceeds the equipment operating limit.', 'Suspend the task under the site weather procedure', 'Continue until the scheduled break'), STEP('Loose material', 'A gust starts moving unsecured sheet material.', 'Secure material and clear the exposed area', 'Catch the sheet near the platform edge'), STEP('Descent route', 'Workers need to return before further deterioration.', 'Use the planned safe access and descent route', 'Take an unapproved ladder shortcut')),
        M('Multi-Level Shutdown Check', 'Complete a complex elevated-work shutdown and clearance.', STEP('Upper platform', 'Maintenance tools remain near an open edge.', 'Account for and secure every tool', 'Leave tools for the next team'), STEP('Exclusion zone', 'A second contractor wants to reopen the area below.', 'Verify overhead work is complete before release', 'Remove the barriers while work continues'), STEP('Final approval', 'The inspection record has not been signed off.', 'Obtain and record authorised closeout', 'Reopen access without final approval')),
      ],
    },
  },
  'cyber-awareness': {
    cover: '/panoramas/cyber-awareness.png', secondCover: '/panoramas/training-room.jpg',
    area: 'Warehouse digital operations office', desk: 'Incident response desk',
    levels: {
      beginner: [
        M('Spot a Phishing Email', 'Recognise common signs of a simulated phishing message.', STEP('Sender address', 'The displayed sender imitates support but uses an unrelated domain.', 'Check the complete sender address', 'Trust the display name alone'), STEP('Email link', 'The message asks for a password through an unfamiliar link.', 'Avoid the link and use the approved service', 'Open the link and enter credentials'), STEP('Reporting option', 'The suspicious email is still in the inbox.', 'Report the email through the approved channel', 'Forward it to everyone as a warning')),
        M('Secure Your Workstation', 'Protect a shared warehouse computer when leaving a shift.', STEP('Unlocked screen', 'A workstation remains signed in after the operator leaves.', 'Lock the session before leaving', 'Leave the session available to coworkers'), STEP('Written password', 'A password is attached to the monitor.', 'Remove the note and use the approved password manager', 'Leave the password visible'), STEP('Shared account', 'A teammate asks to use another operator’s login.', 'Use an individually authorised account', 'Share the personal login with the teammate')),
        M('Unknown USB Device', 'Handle an unexpected device without exposing the network.', STEP('Found USB', 'An unknown USB drive was found near dispatch.', 'Leave it disconnected and follow reporting procedure', 'Plug it into an office PC to identify owner'), STEP('Device label', 'A handwritten label claims the drive contains payroll data.', 'Treat the claim as unverified', 'Trust the label and open the files'), STEP('Help desk', 'The organisation has an incident reporting channel.', 'Record the finding with the help desk', 'Discard the device without reporting')),
        M('Strong Password Choices', 'Choose safer account access practices.', STEP('New password', 'A common short password is suggested for a new account.', 'Create a unique strong password or passphrase', 'Reuse a short password from another account'), STEP('MFA prompt', 'An unexpected sign-in approval appears.', 'Deny and report the unrequested approval', 'Approve the sign-in to dismiss the alert'), STEP('Password storage', 'A team spreadsheet lists shared credentials.', 'Move secrets to the approved secure mechanism', 'Add your own password to the spreadsheet')),
        M('Visitor Information Check', 'Protect delivery and staff data from unauthorised visitors.', STEP('Delivery manifest', 'A visitor asks to photograph a customer manifest.', 'Confirm their authorisation before sharing data', 'Allow the visitor to photograph the manifest'), STEP('Open screen', 'A monitor displays customer details beside reception.', 'Lock or shield the screen from public view', 'Leave customer data visible'), STEP('Visitor badge', 'The visitor has no valid badge or verified appointment.', 'Follow the visitor verification procedure', 'Give them access to the dispatch office')),
      ],
      intermediate: [
        M('Invoice Fraud Verification', 'Verify a payment-change request before it affects a supplier.', STEP('Changed bank details', 'A familiar supplier requests a new bank account by email.', 'Verify the request using a known independent contact', 'Use the bank account supplied in the email'), STEP('Urgent deadline', 'The sender threatens a delivery delay unless paid today.', 'Escalate the unusual urgency for review', 'Skip approvals to meet the deadline'), STEP('Attachment data', 'The attached invoice differs from approved purchasing records.', 'Compare against trusted purchase records', 'Approve it because the logo looks correct')),
        M('Warehouse Ransomware Alert', 'Respond to simulated signs of malware on an operations workstation.', STEP('Ransomware banner', 'A device displays a demand for payment to restore files.', 'Follow the incident response and isolation procedure', 'Pay the demand using a company card'), STEP('Connected share', 'The affected device has access to shared operations files.', 'Notify IT promptly and follow containment instructions', 'Continue using the shared files from the infected PC'), STEP('Evidence preservation', 'The team wants to erase the machine immediately.', 'Preserve evidence as directed by incident response staff', 'Factory reset it before notifying IT')),
        M('Shared Folder Permissions', 'Find and correct excessive warehouse document access.', STEP('Public sharing link', 'A staff roster can be opened by anyone with the link.', 'Restrict the link to authorised staff', 'Post the link in a public group'), STEP('Former employee', 'A former contractor still has folder access.', 'Revoke access after verifying approval', 'Keep the account active indefinitely'), STEP('Access approval', 'No owner is assigned to review folder permissions.', 'Assign an owner and review least-privilege access', 'Give edit access to all visitors')),
        M('Suspicious Login Investigation', 'Handle alerts of unusual account activity.', STEP('Login alert', 'The dashboard shows sign-ins from an unexpected location.', 'Verify the alert with security staff', 'Ignore the location mismatch'), STEP('MFA requests', 'Repeated push requests appear without an attempted login.', 'Reject the requests and notify IT', 'Approve one request to stop the prompts'), STEP('Account session', 'An unfamiliar browser remains signed in.', 'Follow the policy to revoke sessions and reset access', 'Keep the unfamiliar session open')),
        M('Customer Data Email Mistake', 'Contain an accidental disclosure of logistics data.', STEP('Wrong recipient', 'An outgoing manifest email is addressed to an unrelated contact.', 'Stop or recall the message where supported', 'Send the manifest anyway'), STEP('Sensitive attachment', 'The file includes customer identifiers not required for the request.', 'Minimise and protect data before sharing', 'Send every customer field by default'), STEP('Disclosure report', 'A message containing restricted information may have been delivered.', 'Promptly report the suspected exposure', 'Delete the sent email and hide the incident')),
      ],
      advanced: [
        M('Business Email Compromise', 'Handle a coordinated impersonation and payment diversion attempt.', STEP('Executive impersonation', 'A request imitates an executive and bypasses normal approval.', 'Validate the request through an independent approved channel', 'Follow the apparent executive order immediately'), STEP('Lookalike domain', 'A single-letter domain change appears in the sender address.', 'Compare domain and vendor records carefully', 'Rely on the familiar signature'), STEP('Payment escalation', 'The request redirects a large transfer to a new beneficiary.', 'Pause the transfer and escalate under the finance policy', 'Approve the changed recipient without review')),
        M('Supply Chain Portal Compromise', 'Investigate suspicious access to a supplier integration.', STEP('Supplier login', 'A vendor integration signs in from an unusual network.', 'Revalidate the integration with the vendor security contact', 'Whitelist the new network without verification'), STEP('API token', 'An integration token appears in an unsecured ticket.', 'Rotate or revoke the exposed token following policy', 'Reuse the leaked token for testing'), STEP('Shipment changes', 'Several orders were changed by the unfamiliar session.', 'Preserve logs and escalate unauthorised changes', 'Delete audit events to clear alerts')),
        M('Data Exfiltration Warning', 'Investigate signs of unauthorised export of customer data.', STEP('Large export', 'An account creates an unusually large customer report.', 'Check business justification and authorisation', 'Assume every export is approved'), STEP('Unapproved storage', 'The export is aimed at a personal cloud drive.', 'Block unapproved transfer under company policy', 'Allow the personal upload for convenience'), STEP('Audit trail', 'The account owner cannot explain the activity.', 'Preserve evidence and start incident escalation', 'Clear the account history without investigation')),
        M('Privileged Access Emergency', 'Respond to abnormal administrator-account behaviour.', STEP('Admin session', 'A privileged account is active at an unusual hour.', 'Verify business need and monitor the activity', 'Ignore activity because it is an admin account'), STEP('Emergency change', 'A firewall rule is requested without change approval.', 'Follow documented emergency change controls', 'Open the entire network without recording'), STEP('Credential exposure', 'An admin token appears in a shared chat channel.', 'Revoke the token and report the exposure', 'Copy the token to a shared knowledge base')),
        M('Incident Recovery Decision', 'Coordinate a security event without destroying key evidence.', STEP('Affected endpoint', 'An operations device is suspected of hosting malware.', 'Contain the device using the incident playbook', 'Reconnect it to production before clearance'), STEP('Backup validation', 'A recent backup exists but its integrity is unconfirmed.', 'Validate an approved backup before restoration', 'Restore blindly into a live system'), STEP('Recovery authorisation', 'The response team has not approved reopening affected systems.', 'Obtain recovery sign-off and monitoring controls', 'Restore access before security approval')),
      ],
    },
  },
};

// Use existing local illustrations so every inspectable object has a useful,
// module-appropriate image rather than reusing the panorama for every action.
function objectArtwork(moduleKey, name) {
  const term = name.toLowerCase();
  let file;
  if (moduleKey === 'cyber-awareness') {
    if (/email|sender|invoice|payment|request|recipient|supplier|domain/.test(term)) file = 'cyber-email';
    else if (/usb|device/.test(term)) file = 'cyber-usb';
    else if (/visitor|badge/.test(term)) file = 'cyber-visitor';
    else if (/record|document|manifest|attachment|folder|backup|data|report|export|storage/.test(term)) file = 'cyber-documents';
    else if (/token|admin|account|login|mfa|password|screen|session|workstation|endpoint|firewall/.test(term)) file = 'cyber-workstation';
    else file = 'cyber-directory';
  } else if (moduleKey === 'working-at-height') {
    if (/ladder/.test(term)) file = 'height-ladder';
    else if (/rail|edge|platform|deck|floor|scaffold|roof/.test(term)) file = 'height-platform';
    else if (/tool|material/.test(term)) file = 'height-tools';
    else if (/barrier|traffic|trade|zone|pedestrian|area below/.test(term)) file = 'height-barrier';
    else if (/permit|authorisation|inspection|approval|record/.test(term)) file = 'height-permit';
    else if (/gate|entry|access/.test(term)) file = 'height-gate';
    else file = 'height-route';
  } else {
    if (/trolley|jack|cage|wheel|equipment|brake/.test(term)) file = 'manual-trolley';
    else if (/crossing|traffic|junction/.test(term)) file = 'manual-crossing';
    else if (/floor|spill|debris|wrapper/.test(term)) file = 'manual-wet-floor';
    else if (/route|lane|exit|walkway|access/.test(term)) file = 'manual-route';
    else if (/pallet|load|carton|stack|goods|box/.test(term)) file = 'manual-load';
    else file = 'manual-checklist';
  }
  return `/simulation-images/${file}.svg`;
}
const LEVEL_INFO = {
  beginner: { time: 360, penalty: 35, mistakes: 3, points: 80 },
  intermediate: { time: 450, penalty: 55, mistakes: 2, points: 90 },
  advanced: { time: 540, penalty: 80, mistakes: 1, points: 100 },
};
function assemble(moduleKey, details, level, scenario, position) {
  const info = LEVEL_INFO[level];
  const scene = { moduleKey, difficulty: level, key: `library-${moduleKey}-${level}-${position + 1}-v1`,
    title: scenario.title, description: scenario.mission,
    instructions: `Training simulation only. ${scenario.mission} Inspect each marked object, choose the safe response, then visit the safety desk to record your decision. Unsafe choices reduce your score or can end your attempt. Follow your site's approved procedure in real work.`,
    category: 'Immersive 360° safety mission', thumbnail: details.cover, estimatedDurationSeconds: info.time - 60,
    timeLimitSeconds: info.time, incorrectPenalty: info.penalty, completionBonus: 160, maxTimeBonus: 120,
    maxScore: 1000, basePoints: 1, hintPenalty: 0, tieRule: 'faster-time', status: 'active',
    simulation: { mission: scenario.mission, initialFlags: [], scoring: { baseScore: 0, correctActionPoints: info.points, failurePenalty: 100 },
      failure: { maxMistakes: info.mistakes, flags: [], message: 'Unsafe action recorded. Review the situation before restarting.' },
      completion: { threshold: 1, locationId: 'safety-desk', requiredFlags: ['signed-off'], successMessage: `Completed: ${scenario.title}. Your decisions were recorded.` },
      environment: { startingLocationId: 'assessment', locations: [
        { id: 'assessment', name: details.area, panorama: details.cover, connections: [{ targetLocationId: 'safety-desk', label: 'Go to safety desk', requiredActionIds: scenario.steps.map((_, i) => `safe-${i + 1}`).concat(level === 'beginner' ? [] : ['verify']) }] },
        { id: 'safety-desk', name: details.desk, panorama: details.secondCover, connections: [{ targetLocationId: 'assessment', label: 'Return to work zone', requiredActionIds: [] }] },
      ] },
      objects: [], actions: [], hazards: [], objectives: [],
    },
  };
  const simulation = scene.simulation;
  scenario.steps.forEach((step, index) => {
    const num = index + 1, id = `risk-${num}`, safe = `safe-${num}`;
    simulation.objects.push({ id, name: step.name, locationId: 'assessment', description: step.issue, imageUrl: objectArtwork(moduleKey, step.name), yaw: -75 + index * 75, pitch: -8, type: 'equipment' });
    simulation.actions.push({ id: safe, objectId: id, label: step.safe, requiredActionIds: level === 'beginner' || index === 0 ? [] : [`safe-${index}`], points: info.points, feedback: `${step.safe}. The risk has been addressed in this simulated situation.`, resolveHazardIds: [`hazard-${num}`] });
    simulation.actions.push({ id: `unsafe-${num}`, objectId: id, label: step.unsafe, points: 0, unsafe: true, critical: false, penalty: info.penalty, feedback: `${step.unsafe} is not safe here. ${step.issue} Choose the controlled response.` });
    simulation.hazards.push({ id: `hazard-${num}`, name: step.name, locationId: 'assessment', description: step.issue, severity: 'high', triggerActionIds: [`unsafe-${num}`], correctResponseActionId: safe, penalty: info.penalty });
    simulation.objectives.push({ id: `objective-${num}`, label: step.safe, actionIds: [safe], required: true });
  });
  if (level !== 'beginner') {
    simulation.objects.push({ id: 'verification', name: 'Risk verification checklist', locationId: 'assessment', imageUrl: objectArtwork(moduleKey, 'report'), description: 'Recheck that all three simulated hazards were dealt with correctly before closing the work area.', yaw: 150, pitch: -9, type: 'workstation' });
    simulation.actions.push({ id: 'verify', objectId: 'verification', label: 'Review the completed safety controls', requiredActionIds: ['safe-1', 'safe-2', 'safe-3'], points: info.points, feedback: 'All three risk controls were verified.' });
    simulation.objectives.push({ id: 'verification-objective', label: 'Verify the controls before leaving', actionIds: ['verify'], required: true });
  }
  simulation.objects.push({ id: 'report', name: 'Safety decision log', locationId: 'safety-desk', imageUrl: objectArtwork(moduleKey, 'report'), description: `Record the safe responses to ${scenario.title.toLowerCase()}. This is a simulated training record.`, yaw: 0, pitch: -8, type: 'workstation' });
  simulation.actions.push({ id: 'sign-off', objectId: 'report', label: 'Submit safety decision log', requiredActionIds: scenario.steps.map((_, i) => `safe-${i + 1}`).concat(level === 'beginner' ? [] : ['verify']), setFlags: ['signed-off'], points: info.points, feedback: 'Your safety decisions have been submitted successfully.' });
  simulation.objectives.push({ id: 'record', label: 'Submit the safety decision log', actionIds: ['sign-off'], required: true });
  return scene;
}

export const safetyMissionLibrary = Object.entries(SCENARIOS).flatMap(([moduleKey, details]) =>
  Object.entries(details.levels).flatMap(([level, missions]) => missions.map((scenario, i) => assemble(moduleKey, details, level, scenario, i))));
export const SAFETY_MISSION_LIBRARY_COUNT = safetyMissionLibrary.length;
