// Editable scenario examples. Scenario policy is content, never a universal PPE/handling rule.
const room = (id, name, panorama, targets = []) => ({ id, name, panorama, connections: targets.map(targetLocationId => ({ targetLocationId, requiredActionIds: [] })) });
const object = (id, name, locationId, description, yaw = 0, type = 'equipment') => ({ id, name, locationId, description, yaw, pitch: -8, type });
const action = (id, objectId, label, requiredActionIds = [], extra = {}) => ({ id, objectId, label, requiredActionIds, points: 70, feedback: `${label}: completed.`, ...extra });
const objective = (id, label, actionIds, required = true) => ({ id, label, actionIds, required });
const hazard = (id, name, locationId, triggerActionIds, correctResponseActionId, extra = {}) => ({ id, name, locationId, triggerActionIds, correctResponseActionId, penalty: 40, severity: 'high', feedback: name, ...extra });
const settings = (moduleKey, title, mission, panorama) => ({ moduleKey, title, description: mission, instructions: 'Explore the area, interact with equipment and follow the scenario procedure. Move between connected areas to complete the mission.', difficulty: 'beginner', category: 'Safety Simulation Mission', thumbnail: panorama, estimatedDurationSeconds: 300, status: 'draft', timeLimitSeconds: 420, basePoints: 1, incorrectPenalty: 40, completionBonus: 150, maxTimeBonus: 100, maxScore: 1200, tieRule: 'faster-time', simulation: { mission, initialFlags: [], scoring: { baseScore: 0, correctActionPoints: 70, failurePenalty: 100 }, failure: { maxMistakes: 3, flags: [], message: 'Stop work and review the scenario procedure.' }, completion: { threshold: 1, requiredFlags: [], successMessage: 'Mission completed safely.' }, hazards: [] } });

function height() {
  const game = settings('working-at-height', 'Height Safety Mission', 'Inspect access equipment, prepare a guarded platform, complete maintenance and return safely.', '/panoramas/working-height.png');
  game.instructions = 'Scenario procedure: use the inspected, guarded platform for this task. Isolate the work area, secure the tools and keep the access route clear. PPE requirements must be set by the game creator for the actual task.';
  Object.assign(game.simulation, {
    environment: { startingLocationId: 'access', locations: [
      { ...room('access', 'Warehouse access area', '/panoramas/logistics-indoor.png', ['platform']), connections: [{ targetLocationId: 'platform', label: 'Access guarded platform', requiredActionIds: ['inspect-platform', 'barrier', 'secure-tools'] }] },
      room('platform', 'Guarded work platform', '/panoramas/working-height.png', ['access']),
    ] },
    objects: [object('route', 'Access route', 'access', 'Packaging obstructs part of the approach.', -55), object('ladder', 'Damaged ladder', 'access', 'A damaged rung is visible. Inspect and isolate this ladder.', -22), object('platform', 'Guarded platform', 'access', 'Inspect guardrails, floor and approved access. This scenario uses a guarded platform.', 10), object('barrier', 'Safety barrier', 'access', 'Keep people away from the area below the work.', 42), object('tools', 'Maintenance tools', 'access', 'Secure tools against falling, according to the scenario procedure.', 70), object('task', 'Maintenance station', 'platform', 'Complete the planned maintenance from the guarded work position.'), object('exit', 'Access gate', 'access', 'Check out after returning safely.', 95)],
    actions: [action('inspect-route', 'route', 'Inspect approach'), action('clear-route', 'route', 'Clear obstruction', ['inspect-route'], { resolveHazardIds: ['obstructed-access'] }), action('inspect-ladder', 'ladder', 'Inspect ladder'), action('isolate-ladder', 'ladder', 'Tag ladder out of service', ['inspect-ladder'], { resolveHazardIds: ['damaged-ladder'] }), action('use-ladder', 'ladder', 'Climb ladder', [], { unsafe: true, points: 0, critical: true, feedback: 'A damaged ladder must not be used.' }), action('inspect-platform', 'platform', 'Inspect guarded platform', ['clear-route', 'isolate-ladder'], { feedback: 'The inspected platform meets this scenario procedure. No universal harness requirement is assumed.' }), action('barrier', 'barrier', 'Isolate work area', ['inspect-platform'], { resolveHazardIds: ['falling-object'] }), action('secure-tools', 'tools', 'Secure maintenance tools', ['barrier']), action('maintenance', 'task', 'Perform maintenance', ['secure-tools'], { setFlags: ['task-complete'] }), action('lean-out', 'task', 'Reach beyond guardrail', [], { unsafe: true, points: 0, critical: true, feedback: 'Stop: the work position is unsafe.' }), action('check-out', 'exit', 'Finish and check out', ['maintenance'])],
    hazards: [hazard('damaged-ladder', 'Damaged ladder', 'access', ['use-ladder'], 'isolate-ladder', { critical: true }), hazard('obstructed-access', 'Obstructed access', 'access', [], 'clear-route'), hazard('falling-object', 'Falling-object risk', 'platform', ['lean-out'], 'barrier', { critical: true })],
    objectives: [objective('approach', 'Inspect and clear the access route', ['inspect-route', 'clear-route']), objective('safe-access', 'Select safe access equipment', ['inspect-ladder', 'isolate-ladder', 'inspect-platform']), objective('prepare', 'Isolate the area and secure tools', ['barrier', 'secure-tools']), objective('work', 'Complete elevated maintenance', ['maintenance']), objective('leave', 'Return safely and check out', ['check-out'])],
    completion: { ...game.simulation.completion, locationId: 'access', requiredFlags: ['task-complete'], successMessage: 'Maintenance completed. Tools were secured and the worker returned safely.' },
  }); return game;
}
function cyber() {
  const game = settings('cyber-awareness', 'Cyber Incident Mission', 'Investigate a simulated suspicious email, verify the request and report the incident safely.', '/panoramas/cyber-awareness.png');
  game.instructions = 'All messages, files and devices are simulated. No real passwords, attachments, links or malware are used. Verify a request through the approved internal channel before following it.';
  Object.assign(game.simulation, {
    environment: { startingLocationId: 'office', locations: [room('office', 'Cyber office workstation', '/panoramas/cyber-awareness.png', ['response']), room('response', 'Incident response desk', '/panoramas/training-room.jpg', ['office'])] },
    objects: [object('workstation', 'Workstation', 'office', 'A simulated warehouse workstation. No real credentials are collected.', 0, 'workstation'), object('email', 'Suspicious inbox message', 'office', 'SIMULATED EMAIL · From: support@example.invalid · Subject: urgent password verification. The displayed destination does not match the approved internal service.', -35, 'email'), object('attachment', 'Unexpected attachment', 'office', 'SIMULATED FILE · invoice-preview.fake. It is never downloaded or executed.', 35, 'file'), object('usb', 'Unknown USB device', 'office', 'A removable device was found outside the office.', 65, 'device'), object('verify', 'Approved contact directory', 'response', 'Verify the request with the internal team through this simulated channel.', -20, 'workstation'), object('report', 'Incident reporting console', 'response', 'Record the suspicious message and device in the simulated incident report.', 30, 'workstation')],
    actions: [action('inspect-email', 'email', 'Inspect sender and destination', [], { feedback: 'The sender and destination do not match the expected internal service. The request is suspicious.' }), action('open-link', 'email', 'Follow password request', [], { unsafe: true, critical: true, points: 0, feedback: 'Simulated credential disclosure stopped. No credentials were entered.' }), action('quarantine-email', 'email', 'Quarantine message', ['inspect-email'], { resolveHazardIds: ['phishing', 'credential-request'] }), action('inspect-attachment', 'attachment', 'Inspect file details'), action('open-attachment', 'attachment', 'Open unexpected file', [], { unsafe: true, points: 0, feedback: 'Unsafe file interaction simulated. No file was executed.' }), action('isolate-usb', 'usb', 'Isolate unknown device', [], { resolveHazardIds: ['unknown-usb'] }), action('connect-usb', 'usb', 'Connect unknown USB', [], { unsafe: true, points: 0, feedback: 'The simulated device was unsafe to connect.' }), action('lock-workstation', 'workstation', 'Lock workstation', ['quarantine-email']), action('verify-request', 'verify', 'Verify through approved channel', ['inspect-email'], { feedback: 'Internal support confirms it did not send this request.' }), action('report-incident', 'report', 'Submit simulated incident report', ['verify-request', 'inspect-attachment', 'isolate-usb', 'lock-workstation'], { setFlags: ['incident-reported'], resolveHazardIds: ['attachment'] })],
    hazards: [hazard('phishing', 'Phishing request', 'office', ['open-link'], 'quarantine-email', { critical: true }), hazard('credential-request', 'Unverified credential request', 'office', [], 'quarantine-email'), hazard('attachment', 'Suspicious attachment', 'office', ['open-attachment'], 'report-incident'), hazard('unknown-usb', 'Unknown removable device', 'office', ['connect-usb'], 'isolate-usb')],
    objectives: [objective('investigate', 'Inspect suspicious message and file', ['inspect-email', 'inspect-attachment']), objective('contain', 'Quarantine the message and isolate the USB', ['quarantine-email', 'isolate-usb']), objective('secure', 'Lock the workstation before leaving', ['lock-workstation']), objective('verify', 'Verify the request through an approved channel', ['verify-request']), objective('report', 'Report the incident', ['report-incident'])],
    completion: { ...game.simulation.completion, locationId: 'response', requiredFlags: ['incident-reported'], successMessage: 'Incident reported and workstation secured. All cyber activity remained simulated.' },
  }); return game;
}
function manual() {
  const game = settings('manual-handling', 'Warehouse Handling Mission', 'Assess an awkward warehouse load, prepare the route and deliver it using the scenario-approved trolley.', '/panoramas/manual-handling.png');
  game.instructions = 'Scenario policy: this awkward load requires the rated trolley provided. Inspect the load, trolley and route, then secure and move the load. The game creator can change this policy for other loads and procedures.';
  Object.assign(game.simulation, {
    environment: { startingLocationId: 'packing', locations: [
      { ...room('packing', 'Handling and packing area', '/panoramas/manual-handling.png', ['route']), connections: [{ targetLocationId: 'route', label: 'Move along prepared warehouse route', requiredActionIds: ['load-trolley', 'clear-obstacle', 'dry-floor'] }] },
      { ...room('route', 'Loading route', '/panoramas/entrance-storage.png', ['packing', 'destination']), connections: [{ targetLocationId: 'packing', requiredActionIds: [] }, { targetLocationId: 'destination', label: 'Continue to delivery bay', requiredActionIds: ['check-traffic'] }] },
      room('destination', 'Delivery bay', '/panoramas/loading-dispatch.png', ['route']),
    ] },
    objects: [object('load', 'Awkward load', 'packing', 'Inspect weight, shape and stability. This scenario policy requires a rated trolley.', -20, 'load'), object('trolley', 'Rated trolley', 'packing', 'Check condition and suitability before loading.', 20), object('route', 'Route inspection point', 'packing', 'Packaging and a wet patch obstruct the route.', -55), object('obstacle', 'Loose packaging', 'packing', 'Remove the obstacle before moving the trolley.', 55), object('wet-floor', 'Wet floor', 'packing', 'Make the route safe using the scenario procedure.', 85), object('traffic', 'Warehouse crossing', 'route', 'Check the crossing before moving the load through.', 5), object('destination', 'Marked delivery position', 'destination', 'Place and secure the load inside the marked area.', -10)],
    actions: [action('assess-load', 'load', 'Assess load'), action('lift-alone', 'load', 'Lift awkward load unaided', [], { unsafe: true, points: 0, feedback: 'This scenario requires the provided trolley.' }), action('inspect-route', 'route', 'Inspect delivery route'), action('clear-obstacle', 'obstacle', 'Clear loose packaging', ['inspect-route'], { resolveHazardIds: ['obstruction'] }), action('dry-floor', 'wet-floor', 'Make wet route safe', ['inspect-route'], { resolveHazardIds: ['slip'] }), action('inspect-trolley', 'trolley', 'Inspect trolley', ['assess-load']), action('load-trolley', 'load', 'Load and secure trolley', ['inspect-trolley', 'clear-obstacle', 'dry-floor'], { setFlags: ['load-on-trolley'], hiddenAfterActionIds: [], resolveHazardIds: ['awkward-load'] }), action('check-traffic', 'traffic', 'Check crossing and move safely', ['load-trolley'], { requiredFlags: ['load-on-trolley'] }), action('rush-crossing', 'traffic', 'Rush through crossing', [], { unsafe: true, points: 0, feedback: 'Unsafe crossing movement recorded.' }), action('place-load', 'destination', 'Place and secure load', ['check-traffic'], { requiredFlags: ['load-on-trolley'], clearFlags: ['load-on-trolley'], setFlags: ['delivered'] }), action('drop-load', 'destination', 'Leave load across the aisle', [], { unsafe: true, points: 0, feedback: 'The load obstructs the aisle.' })],
    hazards: [hazard('awkward-load', 'Unsafe lifting method', 'packing', ['lift-alone'], 'load-trolley'), hazard('obstruction', 'Obstructed route', 'packing', [], 'clear-obstacle'), hazard('slip', 'Wet floor', 'packing', [], 'dry-floor'), hazard('traffic-risk', 'Collision risk', 'route', ['rush-crossing'], 'check-traffic'), hazard('poor-placement', 'Obstructed delivery aisle', 'destination', ['drop-load'], 'place-load')],
    objectives: [objective('load-assessment', 'Assess load and handling equipment', ['assess-load', 'inspect-trolley']), objective('route-assessment', 'Inspect and clear the route', ['inspect-route', 'clear-obstacle', 'dry-floor']), objective('prepare-load', 'Load and secure the trolley', ['load-trolley']), objective('transport', 'Navigate through the warehouse crossing', ['check-traffic']), objective('delivery', 'Place the load safely at the destination', ['place-load'])],
    completion: { ...game.simulation.completion, locationId: 'destination', requiredFlags: ['delivered'], successMessage: 'Load delivered safely along the prepared route.' },
  }); return game;
}
export const simulationTemplates = { 'working-at-height': height(), 'cyber-awareness': cyber(), 'manual-handling': manual() };
export const simulationProgrammeLevel = value => ({ easy: 'beginner', basic: 'beginner', beginner: 'beginner', medium: 'intermediate', intermediate: 'intermediate', high: 'advanced', advanced: 'advanced' }[String(value || '').trim().toLowerCase()] || 'beginner');
export function simulationTemplate(key) {
  if (simulationTemplates[key]) return JSON.parse(JSON.stringify(simulationTemplates[key]));
  const name = String(key || 'training').replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const game = settings(key, `${name} Mission`, `Inspect the ${name.toLowerCase()} task and follow its approved procedure.`, '/panoramas/training-room.jpg');
  game.instructions = 'Edit this starting mission with the procedure, objects and decisions for this training module before activating it.';
  Object.assign(game.simulation, {
    environment: { startingLocationId: 'training', locations: [room('training', `${name} training area`, '/panoramas/training-room.jpg')] },
    objects: [object('task', `${name} task`, 'training', 'Replace this description with the task for this module.')],
    actions: [action('inspect-task', 'task', 'Inspect the task and confirm the procedure')],
    objectives: [objective('inspect', 'Inspect the module task', ['inspect-task'])],
  });
  return game;
}
// Changing a module must replace the complete content, not just its label.
export function simulationDraftForProgramme(programme) {
  return { ...simulationTemplate(programme.programmeType), moduleKey: programme.programmeType,
    programmeId: String(programme._id), difficulty: simulationProgrammeLevel(programme.level) };
}

function platformPatrol() {
  const game = settings('working-at-height', 'Platform Inspection Patrol', 'Inspect an access platform, isolate defective equipment and record a safe alternative before work starts.', '/panoramas/working-height.png');
  game.instructions = 'This inspection scenario contains a damaged guardrail. Keep the platform closed, protect the area below and record the approved alternative. Do not climb defective equipment.';
  Object.assign(game.simulation, {
    environment: { startingLocationId: 'inspection', locations: [
      { ...room('inspection', 'Platform inspection point', '/panoramas/working-height.png', ['control']), connections: [{ targetLocationId: 'control', label: 'Go to safety control desk', requiredActionIds: ['tag-platform', 'protect-area'] }] },
      room('control', 'Safety control desk', '/panoramas/logistics-indoor.png', ['inspection']),
    ] },
    objects: [object('permit', 'Task permit', 'inspection', 'Check the planned task and the approved access procedure.', -55), object('guardrail', 'Damaged guardrail', 'inspection', 'A loose guardrail joint is visible.', -20), object('floor', 'Platform floor', 'inspection', 'Inspect the floor and access surface.', 15), object('tag', 'Out-of-service tag', 'inspection', 'Close the defective platform to access.', 45), object('barrier', 'Exclusion barrier', 'inspection', 'Protect people below the platform.', 75), object('alternative', 'Alternative access plan', 'control', 'Review the approved inspected alternative for this task.', -20), object('report', 'Inspection record', 'control', 'Record defects, isolation and the selected alternative.', 25)],
    actions: [action('check-permit', 'permit', 'Check task permit'), action('inspect-guardrail', 'guardrail', 'Inspect guardrail'), action('inspect-floor', 'floor', 'Inspect platform floor'), action('climb-platform', 'guardrail', 'Climb defective platform', [], { unsafe: true, critical: true, points: 0, feedback: 'Stop: the platform has a defective guardrail.' }), action('tag-platform', 'tag', 'Tag platform out of service', ['check-permit', 'inspect-guardrail', 'inspect-floor'], { resolveHazardIds: ['defective-platform'] }), action('protect-area', 'barrier', 'Protect the area below', ['tag-platform'], { resolveHazardIds: ['unprotected-area'] }), action('select-alternative', 'alternative', 'Confirm approved alternative', ['protect-area']), action('record-inspection', 'report', 'Submit inspection record', ['select-alternative'], { setFlags: ['inspection-recorded'] })],
    hazards: [hazard('defective-platform', 'Defective guardrail', 'inspection', ['climb-platform'], 'tag-platform', { critical: true }), hazard('unprotected-area', 'Unprotected area below', 'inspection', [], 'protect-area')],
    objectives: [objective('inspection', 'Check the permit, guardrail and floor', ['check-permit', 'inspect-guardrail', 'inspect-floor']), objective('isolation', 'Close the platform and protect the area', ['tag-platform', 'protect-area']), objective('alternative', 'Confirm approved alternative access', ['select-alternative']), objective('record', 'Submit the inspection record', ['record-inspection'])],
    completion: { ...game.simulation.completion, locationId: 'control', requiredFlags: ['inspection-recorded'], successMessage: 'Defective access isolated and the alternative recorded.' },
  }); return game;
}

function cleanDesk() {
  const game = settings('cyber-awareness', 'Clean Desk Challenge', 'Secure documents and a workstation, verify an unexpected visitor and report the exposure.', '/panoramas/cyber-awareness.png');
  game.instructions = 'Use the simulated visitor procedure. Do not share documents or unlock a workstation for an unverified visitor. All records and interactions are fictional.';
  Object.assign(game.simulation, {
    environment: { startingLocationId: 'office', locations: [
      { ...room('office', 'Warehouse office', '/panoramas/cyber-awareness.png', ['reporting']), connections: [{ targetLocationId: 'reporting', label: 'Go to incident reporting desk', requiredActionIds: ['secure-documents', 'deny-access'] }] },
      room('reporting', 'Reporting desk', '/panoramas/training-room.jpg', ['office']),
    ] },
    objects: [object('documents', 'Exposed dispatch documents', 'office', 'Fictional customer information is visible on an unattended desk.', -50), object('screen', 'Unlocked workstation', 'office', 'Secure the unattended workstation.', -15, 'workstation'), object('cabinet', 'Lockable document cabinet', 'office', 'Store sensitive documents securely.', 20), object('visitor', 'Unexpected visitor', 'office', 'The visitor requests access without an approved appointment.', 55), object('report', 'Exposure reporting console', 'reporting', 'Record the document exposure and unverified visitor.', 5, 'workstation')],
    actions: [action('inspect-documents', 'documents', 'Identify exposed information'), action('share-documents', 'documents', 'Hand documents to visitor', [], { unsafe: true, critical: true, points: 0, feedback: 'Simulated disclosure stopped. Verify authorisation before sharing information.' }), action('lock-screen', 'screen', 'Lock unattended workstation', [], { resolveHazardIds: ['unlocked-screen'] }), action('secure-documents', 'cabinet', 'Store and lock documents', ['inspect-documents', 'lock-screen'], { resolveHazardIds: ['document-exposure'] }), action('verify-visitor', 'visitor', 'Check visitor authorisation', [], { feedback: 'No approved appointment or authorisation is recorded.' }), action('deny-access', 'visitor', 'Refer visitor to reception', ['verify-visitor'], { resolveHazardIds: ['unverified-visitor'] }), action('grant-access', 'visitor', 'Allow unverified visitor access', [], { unsafe: true, points: 0, feedback: 'Unverified access is unsafe in this scenario.' }), action('report-exposure', 'report', 'Report the exposure', ['secure-documents', 'deny-access'], { setFlags: ['exposure-reported'] })],
    hazards: [hazard('document-exposure', 'Exposed information', 'office', ['share-documents'], 'secure-documents', { critical: true }), hazard('unlocked-screen', 'Unlocked workstation', 'office', [], 'lock-screen'), hazard('unverified-visitor', 'Unverified visitor', 'office', ['grant-access'], 'deny-access')],
    objectives: [objective('documents', 'Identify and secure sensitive documents', ['inspect-documents', 'secure-documents']), objective('screen', 'Lock the workstation', ['lock-screen']), objective('visitor', 'Verify and refer the visitor', ['verify-visitor', 'deny-access']), objective('report', 'Report the exposure', ['report-exposure'])],
    completion: { ...game.simulation.completion, locationId: 'reporting', requiredFlags: ['exposure-reported'], successMessage: 'Documents and workstation secured; exposure reported.' },
  }); return game;
}

function dispatchRoute() {
  const game = settings('manual-handling', 'Dispatch Route Challenge', 'Inspect a pallet load, prepare a clear dispatch route and deliver it with the provided pallet jack.', '/panoramas/loading-dispatch.png');
  game.instructions = 'Scenario policy: use the inspected pallet jack for this pallet. Keep exits clear, secure the load and stop to check the vehicle crossing before entering the dispatch bay.';
  Object.assign(game.simulation, {
    environment: { startingLocationId: 'loading', locations: [
      { ...room('loading', 'Pallet preparation area', '/panoramas/manual-handling.png', ['crossing']), connections: [{ targetLocationId: 'crossing', label: 'Move pallet to crossing', requiredActionIds: ['secure-pallet', 'clear-exit', 'inspect-jack'] }] },
      { ...room('crossing', 'Dispatch vehicle crossing', '/panoramas/entrance-storage.png', ['loading', 'bay']), connections: [{ targetLocationId: 'loading', requiredActionIds: [] }, { targetLocationId: 'bay', label: 'Enter dispatch bay', requiredActionIds: ['check-crossing'] }] },
      room('bay', 'Dispatch bay', '/panoramas/loading-dispatch.png', ['crossing']),
    ] },
    objects: [object('pallet', 'Unsecured pallet load', 'loading', 'Check the pallet, weight label and load stability.', -35, 'load'), object('jack', 'Pallet jack', 'loading', 'Check the jack condition and rated capacity.', 5), object('exit', 'Blocked exit route', 'loading', 'Loose cartons obstruct the marked exit route.', 45), object('crossing', 'Vehicle crossing', 'crossing', 'Stop and check for vehicle traffic.', 0), object('bay', 'Marked pallet position', 'bay', 'Lower the pallet inside the marked storage position.', -15), object('record', 'Dispatch checklist', 'bay', 'Record safe delivery and a clear aisle.', 25)],
    actions: [action('inspect-pallet', 'pallet', 'Inspect pallet and load'), action('secure-pallet', 'pallet', 'Secure and balance pallet load', ['inspect-pallet'], { setFlags: ['pallet-secured'], resolveHazardIds: ['unstable-load'] }), action('move-unsecured', 'pallet', 'Move unsecured pallet', [], { unsafe: true, points: 0, feedback: 'Secure and balance the pallet before moving.' }), action('inspect-jack', 'jack', 'Inspect pallet jack', ['inspect-pallet']), action('clear-exit', 'exit', 'Clear marked exit route', [], { resolveHazardIds: ['blocked-exit'] }), action('check-crossing', 'crossing', 'Stop and check vehicle crossing', ['secure-pallet', 'inspect-jack', 'clear-exit'], { requiredFlags: ['pallet-secured'], resolveHazardIds: ['vehicle-risk'] }), action('rush-crossing', 'crossing', 'Cross without checking', [], { unsafe: true, points: 0, feedback: 'Stop and check the vehicle route before crossing.' }), action('lower-pallet', 'bay', 'Lower pallet into marked position', ['check-crossing'], { clearFlags: ['pallet-secured'], setFlags: ['pallet-delivered'] }), action('finish-checklist', 'record', 'Complete dispatch checklist', ['lower-pallet'], { requiredFlags: ['pallet-delivered'] })],
    hazards: [hazard('unstable-load', 'Unstable pallet load', 'loading', ['move-unsecured'], 'secure-pallet'), hazard('blocked-exit', 'Blocked exit route', 'loading', [], 'clear-exit'), hazard('vehicle-risk', 'Vehicle collision risk', 'crossing', ['rush-crossing'], 'check-crossing')],
    objectives: [objective('pallet', 'Inspect and secure the pallet', ['inspect-pallet', 'secure-pallet']), objective('route', 'Check equipment and clear the exit', ['inspect-jack', 'clear-exit']), objective('crossing', 'Check the vehicle crossing', ['check-crossing']), objective('delivery', 'Place the pallet and complete the checklist', ['lower-pallet', 'finish-checklist'])],
    completion: { ...game.simulation.completion, locationId: 'bay', requiredFlags: ['pallet-delivered'], successMessage: 'Pallet delivered and the dispatch checklist completed.' },
  }); return game;
}

export const simulationSamples = [
  { key: 'height-maintenance-v1', ...simulationTemplate('working-at-height') },
  { key: 'platform-inspection-v1', ...platformPatrol() },
  { key: 'cyber-incident-v1', ...simulationTemplate('cyber-awareness') },
  { key: 'clean-desk-v1', ...cleanDesk() },
  { key: 'warehouse-handling-v1', ...simulationTemplate('manual-handling') },
  { key: 'dispatch-route-v1', ...dispatchRoute() },
];
