import { useEffect, useMemo, useState } from "react";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import api, { API_BASE_URL } from "../../services/api";

const origin = API_BASE_URL.replace(/\/api\/?$/, "");
const url = (value) => !value ? "" : /^https?:\/\//i.test(value) ? value : `${origin}${value}`;
const blank = { type: "warehouse_tour", programme: "", area: "", name: "", description: "", status: "pending" };
const blankHotspot = () => ({ label: "", targetPanorama: "", yaw: 0, pitch: -5 });

export default function PanoramaManagementPage() {
    const [items, setItems] = useState([]), [programmes, setProgrammes] = useState([]), [form, setForm] = useState(blank), [hotspots, setHotspots] = useState([]), [file, setFile] = useState(null), [editing, setEditing] = useState(null), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
    const load = async () => { setLoading(true); setError(""); try { const [a, b] = await Promise.all([api.get("/panoramas"), api.get("/programmes")]); setItems(a.data?.panoramas || []); setProgrammes(b.data?.programmes || []) } catch (e) { setError(e.response?.data?.message || "Unable to load panorama management data.") } finally { setLoading(false) } };
    useEffect(() => { load() }, []);
    const reset = () => { setEditing(null); setForm(blank); setHotspots([]); setFile(null); setError(""); setSuccess("") };
    const edit = (p) => { setEditing(p); setForm({ type: p.type || "warehouse_tour", programme: p.programme?._id || p.programme || "", area: p.area || "", name: p.name || "", description: p.description || "", status: p.status || "pending" }); setHotspots((p.hotspots || []).map(h => ({ ...h, targetPanorama: h.targetPanorama?._id || h.targetPanorama || "" }))); setFile(null); setError(""); setSuccess("") };
    const validateFile = async (f) => { if (!f) return true; return new Promise(resolve => { const img = new Image(); const object = URL.createObjectURL(f); img.onload = () => { const ok = Math.abs(img.width / img.height - 2) <= 0.01; URL.revokeObjectURL(object); if (!ok) setError(`Panorama must be 2:1. Selected image is ${img.width}×${img.height}.`); resolve(ok) }; img.onerror = () => { URL.revokeObjectURL(object); setError("Unable to read the selected image."); resolve(false) }; img.src = object }) };
    const save = async (e) => { e.preventDefault(); setError(""); setSuccess(""); if (!form.name.trim()) return setError("Panorama name is required."); if (form.type === "training_module" && !form.programme) return setError("Select the programme for this module panorama."); if (form.type !== "training_module" && form.programme) return setError("Warehouse panoramas cannot be attached to a training programme."); if (!editing && !file) return setError("Choose a 2:1 panorama image."); if (!(await validateFile(file))) return; setSaving(true); try { const body = new FormData(); Object.entries(form).forEach(([k, v]) => body.append(k, v)); body.append("hotspots", JSON.stringify(hotspots.map(h => ({ ...h, yaw: Number(h.yaw), pitch: Number(h.pitch), targetPanorama: h.targetPanorama || null })))); if (file) body.append("panorama", file); if (editing) await api.patch(`/panoramas/${editing._id}`, body); else await api.post("/panoramas", body); setSuccess(editing ? "Panorama updated successfully." : "Panorama created successfully."); await load(); if (!editing) { setForm(blank); setHotspots([]); setFile(null) } } catch (e2) { setError(e2.response?.data?.message || "Unable to save panorama.") } finally { setSaving(false) } };
    const counts = useMemo(() => ({ tour: items.filter(x => x.type !== "training_module").length, module: items.filter(x => x.type === "training_module").length, active: items.filter(x => x.status === "active").length }), [items]);
    return <DashboardLayout role="admin" showHeader={false}><div className="app-page space-y-5">
        <section className="training-hero rounded-xl px-6 py-6 shadow-sm"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-blue-100">Sprint 2 · B10</p><h1 className="mt-1 text-[22px] font-bold !text-white">Panorama & Hotspot Management</h1><p className="mt-2 text-[11px] text-blue-100">Warehouse Tour, warehouse areas and training-module panoramas are stored separately. Images are validated as 2:1 on the client and server.</p></section>
        {(error || success) && <div className={`rounded-lg border p-3 text-[11px] ${error ? "border-red-200 bg-red-50 text-red-700" : "border-green-200 bg-green-50 text-green-700"}`}>{error || success}</div>}
        <div className="grid gap-3 sm:grid-cols-3">{[["Warehouse panoramas", counts.tour], ["Module panoramas", counts.module], ["Active", counts.active]].map(([l, v]) => <div key={l} className="rounded-xl border bg-white p-4"><p className="text-[9px] text-slate-500">{l}</p><b className="text-2xl">{v}</b></div>)}</div>
        <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
            <section className="overflow-hidden rounded-xl border bg-white"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-bold">Configured panoramas</h2><p className="text-[9px] text-slate-500">Warehouse and module records remain isolated.</p></div><button onClick={reset} className="rounded-lg bg-[#0b4f87] px-4 py-2 text-[10px] text-white">+ New panorama</button></div>{loading ? <p className="p-5 text-sm">Loading...</p> : items.length ? <div className="overflow-x-auto"><table className="w-full text-left text-[10px]"><thead className="bg-slate-50"><tr><th className="p-3">Preview</th><th>Name</th><th>Type</th><th>Programme/Area</th><th>Status</th><th></th></tr></thead><tbody>{items.map(p => <tr key={p._id} className="border-t"><td className="p-3">{p.imageUrl ? <img src={url(p.imageUrl)} alt={p.name} className="h-12 w-24 rounded object-cover" /> : <span>Missing</span>}</td><td>{p.name}</td><td>{p.type}</td><td>{p.programme?.title || p.area || "—"}</td><td>{p.status}</td><td><button onClick={() => edit(p)} className="rounded border px-2 py-1">Edit</button></td></tr>)}</tbody></table></div> : <p className="p-5 text-[10px] text-slate-500">No panorama records yet.</p>}</section>
            <form onSubmit={save} className="rounded-xl border bg-white p-5"><h2 className="font-bold">{editing ? "Edit panorama" : "Create panorama"}</h2><div className="mt-4 space-y-3"><Field label="Name" value={form.name} onChange={v => setForm({ ...form, name: v })} /><label className="block text-[10px] font-semibold">Type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value, programme: e.target.value === "training_module" ? form.programme : "" })} className="mt-1 h-10 w-full rounded border px-3"><option value="warehouse_tour">Warehouse Tour</option><option value="warehouse_area">Warehouse Area</option><option value="training_module">Training Module</option></select></label>{form.type === "training_module" ? <label className="block text-[10px] font-semibold">Programme<select required value={form.programme} onChange={e => setForm({ ...form, programme: e.target.value })} className="mt-1 h-10 w-full rounded border px-3"><option value="">Select programme</option>{programmes.map(p => <option key={p._id} value={p._id}>{p.title}</option>)}</select></label> : <Field label="Warehouse area ID" value={form.area} onChange={v => setForm({ ...form, area: v })} />}<label className="block text-[10px] font-semibold">Description<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="mt-1 min-h-20 w-full rounded border p-2" /></label><label className="block text-[10px] font-semibold">Status<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className="mt-1 h-10 w-full rounded border px-3"><option value="pending">Pending</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="block text-[10px] font-semibold">2:1 equirectangular image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => setFile(e.target.files?.[0] || null)} className="mt-1 block w-full rounded border p-2" /></label>
                <div className="border-t pt-3"><div className="flex justify-between"><b className="text-[11px]">Hotspots</b><button type="button" onClick={() => setHotspots(h => [...h, blankHotspot()])} className="rounded border px-2 py-1 text-[9px]">+ Add</button></div>{hotspots.map((h, i) => <div key={i} className="mt-2 rounded bg-slate-50 p-3"><Field label="Label" value={h.label} onChange={v => setHotspots(a => a.map((x, n) => n === i ? { ...x, label: v } : x))} /><div className="grid grid-cols-2 gap-2"><Field label="Yaw" type="number" value={h.yaw} onChange={v => setHotspots(a => a.map((x, n) => n === i ? { ...x, yaw: v } : x))} /><Field label="Pitch" type="number" value={h.pitch} onChange={v => setHotspots(a => a.map((x, n) => n === i ? { ...x, pitch: v } : x))} /></div><label className="mt-2 block text-[9px]">Target panorama<select value={h.targetPanorama || ""} onChange={e => setHotspots(a => a.map((x, n) => n === i ? { ...x, targetPanorama: e.target.value } : x))} className="mt-1 h-9 w-full rounded border px-2"><option value="">Information/no target</option>{items.filter(x => x._id !== (editing?._id || "") && x.type === form.type).map(x => <option key={x._id} value={x._id}>{x.name}</option>)}</select></label><button type="button" onClick={() => setHotspots(a => a.filter((_, n) => n !== i))} className="mt-2 text-[9px] text-red-600">Remove</button></div>)}</div>
                <div className="flex gap-2 pt-2"><button disabled={saving} className="rounded-lg bg-[#0b4f87] px-4 py-2 text-[10px] text-white disabled:opacity-50">{saving ? "Saving..." : editing ? "Save changes" : "Create panorama"}</button>{editing && <button type="button" onClick={reset} className="rounded-lg border px-4 py-2 text-[10px]">Cancel</button>}</div></div></form>
        </div></div></DashboardLayout>;
}
function Field({ label, value, onChange, type = "text" }) { return <label className="block text-[10px] font-semibold">{label}<input type={type} value={value ?? ""} onChange={e => onChange(e.target.value)} className="mt-1 h-10 w-full rounded border px-3" /></label> }
