import { useEffect, useMemo, useState } from "react";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import api, { API_BASE_URL } from "../../services/api";
const emptyForm = { locationId: "", name: "", description: "", order: 0, active: true };
const imageUrl = (v) => !v ? "" : /^https?:\/\//i.test(v) ? v : `${API_BASE_URL.replace(/\/api\/?$/, "")}${v}`;
export default function PanoramaManagementPage() {
    const [locations, setLocations] = useState([]), [selected, setSelected] = useState(null), [form, setForm] = useState(emptyForm), [file, setFile] = useState(null), [hotspots, setHotspots] = useState([]), [notice, setNotice] = useState(""), [error, setError] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
    const load = async () => { setLoading(true); try { const { data } = await api.get("/admin/panoramas"); setLocations(data.locations || []) } catch (e) { setError(e.response?.data?.message || "Unable to load panorama locations.") } finally { setLoading(false) } };
    useEffect(() => { load() }, []);
    const reset = () => { setSelected(null); setForm(emptyForm); setFile(null); setHotspots([]); setNotice(""); setError("") };
    const edit = x => { setSelected(x); setForm({ locationId: x.locationId, name: x.name, description: x.description || "", order: x.order || 0, active: x.active !== false }); setHotspots((x.hotspots || []).map(h => ({ ...h }))); setFile(null); setNotice(""); setError("") };
    const changeHotspot = (i, k, v) => setHotspots(a => a.map((h, n) => n === i ? { ...h, [k]: v } : h));
    const submit = async e => { e.preventDefault(); setSaving(true); setError(""); setNotice(""); try { const body = new FormData(); Object.entries(form).forEach(([k, v]) => body.append(k, String(v))); body.append("hotspots", JSON.stringify(hotspots)); if (file) body.append("panorama", file); if (selected) await api.patch(`/admin/panoramas/${selected._id}`, body); else await api.post("/admin/panoramas", body); setNotice(selected ? "Panorama scene updated successfully." : "Panorama scene created successfully."); await load(); if (!selected) { setForm(emptyForm); setHotspots([]); setFile(null) } } catch (e2) { setError(e2.response?.data?.message || "Unable to save panorama scene.") } finally { setSaving(false) } };
    const deactivate = async x => { if (!window.confirm(`Deactivate ${x.name}?`)) return; try { await api.delete(`/admin/panoramas/${x._id}`); setNotice("Scene deactivated."); await load() } catch (e) { setError(e.response?.data?.message || "Unable to deactivate scene.") } };
    const active = useMemo(() => locations.filter(x => x.active).length, [locations]);
    return <DashboardLayout role="admin" showHeader={false}><div className="app-page space-y-5">
        <section className="training-hero rounded-xl px-6 py-6 shadow-sm"><p className="text-[8px] font-semibold uppercase tracking-[.14em] text-blue-100">Sprint 2 · Admin</p><h1 className="mt-1 text-[20px] font-bold !text-white">Panorama & Scene Management</h1><p className="mt-2 max-w-[760px] text-[10px] leading-5 text-blue-100">Manage Warehouse Tour scenes, replace 2:1 panoramic images and configure MongoDB navigation hotspots used by Trainees.</p></section>
        {(notice || error) && <div className={`rounded-lg border px-4 py-3 text-[11px] ${error ? "border-red-200 bg-red-50 text-red-700" : "border-green-200 bg-green-50 text-green-700"}`}>{error || notice}</div>}
        <div className="grid gap-4 sm:grid-cols-3">{[["Total Scenes", locations.length], ["Active Scenes", active], ["Hotspots", locations.reduce((n, x) => n + (x.hotspots?.length || 0), 0)]].map(([l, v]) => <div key={l} className="rounded-xl border border-[#dbe4ef] bg-white p-5 shadow-sm"><p className="text-[9px] text-[#64748b]">{l}</p><p className="mt-2 text-[23px] font-bold">{v}</p></div>)}</div>
        <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
            <section className="overflow-hidden rounded-xl border border-[#dbe4ef] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#e8eef5] px-5 py-4"><div><h2 className="text-[13px] font-bold">Warehouse Tour Scenes</h2><p className="mt-1 text-[9px] text-[#64748b]">Admin-controlled panorama records.</p></div><button onClick={reset} className="rounded-lg bg-[#0b4f87] px-4 py-2 text-[10px] font-semibold text-white">+ New Scene</button></div>
                {loading ? <p className="p-6 text-[10px]">Loading...</p> : <div className="overflow-x-auto"><table className="w-full text-left text-[10px]"><thead className="bg-[#f8fafc] text-[#52627a]"><tr><th className="px-4 py-3">Preview</th><th>Name</th><th>ID</th><th>Status</th><th>Hotspots</th><th>Actions</th></tr></thead><tbody>{locations.map(x => <tr key={x._id} className="border-t border-[#edf2f7]"><td className="px-4 py-3"><img src={imageUrl(x.panorama)} className="h-12 w-20 rounded-md object-cover" alt="" /></td><td className="font-semibold">{x.name}</td><td>{x.locationId}</td><td>{x.active ? "Active" : "Inactive"}</td><td>{x.hotspots?.length || 0}</td><td><div className="flex gap-2"><button onClick={() => edit(x)} className="rounded border border-[#cbd5e1] px-2 py-1">Edit</button>{x.active && <button onClick={() => deactivate(x)} className="rounded border border-red-200 px-2 py-1 text-red-600">Deactivate</button>}</div></td></tr>)}</tbody></table>{!locations.length && <p className="p-6 text-[10px] text-[#64748b]">No scenes yet.</p>}</div>}</section>
            <section className="rounded-xl border border-[#dbe4ef] bg-white p-5 shadow-sm"><h2 className="text-[13px] font-bold">{selected ? `Edit ${selected.name}` : "Create Panorama Scene"}</h2><p className="mt-1 text-[9px] text-[#64748b]">JPG, PNG or WebP. A 2:1 equirectangular image is recommended.</p><form onSubmit={submit} className="mt-5 space-y-4">
                <div className="grid gap-3 sm:grid-cols-2"><Field label="Scene name" value={form.name} onChange={v => setForm({ ...form, name: v })} /><Field label="Location ID" value={form.locationId} disabled={!!selected} onChange={v => setForm({ ...form, locationId: v })} /></div>
                <label className="block text-[9px] font-semibold">Description<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="mt-1 min-h-20 w-full rounded-lg border border-[#cbd5e1] p-3 text-[10px]" /></label>
                <div className="grid gap-3 sm:grid-cols-2"><Field label="Display order" type="number" value={form.order} onChange={v => setForm({ ...form, order: v })} /><label className="text-[9px] font-semibold">Status<select value={String(form.active)} onChange={e => setForm({ ...form, active: e.target.value === 'true' })} className="mt-1 h-10 w-full rounded-lg border border-[#cbd5e1] px-3 text-[10px]"><option value="true">Active</option><option value="false">Inactive</option></select></label></div>
                <label className="block text-[9px] font-semibold">Panorama image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => setFile(e.target.files?.[0] || null)} className="mt-1 block w-full rounded-lg border border-[#cbd5e1] p-2 text-[9px]" /></label>
                <div className="border-t border-[#e8eef5] pt-4"><div className="flex justify-between"><div><h3 className="text-[11px] font-bold">Navigation Hotspots</h3><p className="text-[8px] text-[#64748b]">Store target, yaw and pitch in MongoDB.</p></div><button type="button" onClick={() => setHotspots(h => [...h, { id: `hotspot-${Date.now()}`, type: "navigation", label: "", yaw: 0, pitch: 0, targetLocationId: "" }])} className="rounded border border-[#cbd5e1] px-3 text-[9px]">+ Add</button></div><div className="mt-3 space-y-3">{hotspots.map((h, i) => <div key={h.id || i} className="rounded-lg bg-[#f8fafc] p-3"><div className="grid grid-cols-2 gap-2"><Field label="Label" value={h.label} onChange={v => changeHotspot(i, "label", v)} /><Field label="Target ID" value={h.targetLocationId || ""} onChange={v => changeHotspot(i, "targetLocationId", v)} /><Field label="Yaw" type="number" value={h.yaw} onChange={v => changeHotspot(i, "yaw", Number(v))} /><Field label="Pitch" type="number" value={h.pitch} onChange={v => changeHotspot(i, "pitch", Number(v))} /></div><button type="button" onClick={() => setHotspots(a => a.filter((_, n) => n !== i))} className="mt-2 text-[8px] font-semibold text-red-600">Remove</button></div>)}</div></div>
                <div className="flex gap-2"><button disabled={saving} className="rounded-lg bg-[#0b4f87] px-4 py-2.5 text-[10px] font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : selected ? "Save Changes" : "Create Scene"}</button>{selected && <button type="button" onClick={reset} className="rounded-lg border border-[#cbd5e1] px-4 py-2.5 text-[10px]">Cancel</button>}</div>
            </form></section>
        </div>
    </div></DashboardLayout>
}
function Field({ label, value, onChange, type = "text", disabled = false }) { return <label className="text-[9px] font-semibold">{label}<input required={label === "Scene name" || label === "Location ID"} disabled={disabled} type={type} value={value} onChange={e => onChange(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#cbd5e1] px-3 text-[10px] disabled:bg-slate-100" /></label> }
